import { TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { signal } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { Observable, Subject, of } from 'rxjs';
import { MappingProfileDialogComponent } from './mapping-profile-dialog.component';
import { MappingProfileDialogV2Component } from '../mapping-profile-dialog-v2/mapping-profile-dialog-v2.component';
import { FieldMappingCanvasComponent } from '../../../components/node-library/destination-wizard/field-mapping/field-mapping-canvas.component';
import { DIALOG_DATA, DialogRef } from '../../../core/services/dialog.service';
import { MappingProfileService } from '../../services/mapping-profile.service';
import { DestinationSchemaService } from '../../../services/destination-schema.service';
import { PermissionActionGuard } from '../../../auth/services/permission-action-guard.service';
import { MappingCatalogService } from '../../../services/mapping-catalog.service';
import { ToastService } from '../../../services/toast.service';
import { TransformationRulesService } from '../../../components/node-library/destination-wizard/field-mapping/transformation-rules.service';

/** The mapping profile dialog used to name its target in three places: a required Destination Object field, a
 *  toolbar Table/Collection/File name field, and the canvas's own table picker. Destination Object is gone and
 *  optional; the toolbar box shows only where the canvas has no picker (CSV-type destinations, and SQL once its
 *  table list has finished loading with nothing to pick). Runs against both copies: v2 is the one the Settings
 *  list opens; v1 is kept in step with it. */
const DIALOGS = [['v2 (opened by Settings)', MappingProfileDialogV2Component], ['v1', MappingProfileDialogComponent]] as const;

for (const [variant, Dialog] of DIALOGS) {
describe(`Mapping profile dialog ${variant} — where the target is named`, () => {
  const column = (name: string, pk = false) => ({ name, dataType: 'nvarchar', mappingValueType: 'String', isNullable: !pk, maxLength: 200, isPrimaryKey: pk, isUnique: pk, isAutoGenerated: false });
  const table = (name: string) => ({ schemaName: 'dbo', tableName: name, fullName: 'dbo.' + name, columns: [column('PatientId', true)] });
  const keyField = { targetField: 'PatientId', jsonPath: '$.id', valueType: 'String', isRequired: true, arrayPolicy: 'Scalar', isUpsertKey: true, isEnabled: true };

  type Schema = () => Observable<unknown>;

  async function mount(o: { dests: Record<string, string>; schema: Record<string, Schema>; mode?: 'create' | 'edit' | 'view'; profile?: unknown }) {
    const create = jasmine.createSpy('create').and.returnValue(of({}));
    const update = jasmine.createSpy('update').and.returnValue(of({}));
    await TestBed.configureTestingModule({
      imports: [Dialog],
      providers: [
        provideHttpClient(),
        provideHttpClientTesting(),
        { provide: DIALOG_DATA, useValue: { mode: o.mode ?? 'create', mappingProfile: o.profile } },
        { provide: DialogRef, useValue: { fillContent: signal(false), close: jasmine.createSpy('close') } },
        { provide: MappingProfileService, useValue: { create, update } },
        { provide: DestinationSchemaService, useValue: { getSchema: (id: string) => o.schema[id]() } },
        { provide: PermissionActionGuard, useValue: { ensure: () => true } },
        { provide: MappingCatalogService, useValue: { fields: () => of([]) } },
        { provide: ToastService, useValue: { show: jasmine.createSpy(), success: jasmine.createSpy(), warning: jasmine.createSpy(), error: jasmine.createSpy() } },
        { provide: TransformationRulesService, useValue: {
            getNodeSchemas: () => of([]), getEffectiveRules: () => of([]), delete: () => of(void 0),
          } },
      ],
    }).compileComponents();

    const fixture = TestBed.createComponent<MappingProfileDialogComponent | MappingProfileDialogV2Component>(Dialog);
    fixture.detectChanges();
    for (const req of TestBed.inject(HttpTestingController).match(() => true)) {
      req.flush(req.request.url.toLowerCase().includes('destination')
        ? Object.entries(o.dests).map(([id, destinationType]) => ({ id, name: id, destinationType }))
        : [{ id: 's1', name: 'Source' }]);
    }
    const dialog = fixture.componentInstance;
    const settle = async () => { fixture.detectChanges(); await fixture.whenStable(); fixture.detectChanges(); };
    const el = fixture.nativeElement as HTMLElement;
    return {
      fixture, dialog, settle, create, update,
      choose: async (destinationId: string) => {
        dialog.metaForm.patchValue({ name: 'P', resourceType: 'Patient', sourceConnectionId: 's1' });
        dialog.metaForm.controls.destinationId.setValue(destinationId);
        await settle();
      },
      canvas: () => fixture.debugElement.query(By.directive(FieldMappingCanvasComponent)).componentInstance as FieldMappingCanvasComponent,
      box: () => el.querySelector<HTMLInputElement>('#mpc-target'),
      boxLabel: () => el.querySelector('label[for="mpc-target"]')?.textContent?.trim(),
      typeInBox: async (value: string) => {
        const input = el.querySelector<HTMLInputElement>('#mpc-target')!;
        input.value = value;
        input.dispatchEvent(new Event('input'));
        await settle();
      },
      destinationObjectField: () => el.querySelector('#mpd-destinationObject'),
      tableDropdown: () => el.querySelector('select#mpc-target'),
      // create(request) vs update(id, request).
      savedDestinationObject: () => (dialog.isCreate ? create.calls.mostRecent()?.args[0] : update.calls.mostRecent()?.args[1])?.destinationObject,
    };
  }

  it('resource type chosen but no destination yet: no box, and the list says to choose a destination', async () => {
    const v = await mount({ dests: { d1: 'Csv' }, schema: { d1: () => of({ tables: [] }) } });
    v.dialog.metaForm.patchValue({ name: 'P', resourceType: 'Patient', sourceConnectionId: 's1' });
    await v.settle();
    expect(v.box()).toBeNull();
    const list = v.fixture.debugElement.query(By.css('app-field-mapping-list'));
    (list.componentInstance as { collapsed: { set(value: boolean): void } }).collapsed.set(false);
    await v.settle();
    expect((v.fixture.nativeElement as HTMLElement).querySelector('.fm-list-empty')?.textContent?.trim())
      .toBe('Choose a destination above first, then you can add mappings here.');

    v.dialog.metaForm.controls.destinationId.setValue('d1');
    await v.settle();
    expect(v.boxLabel()).toBe('File name');
  });

  it('SQL with tables: no Destination Object, no toolbar picker; the canvas pick is saved', async () => {
    const v = await mount({ dests: { d1: 'PostgreSql' }, schema: { d1: () => of({ tables: [table('A')] }) } });
    await v.choose('d1');
    expect(v.destinationObjectField()).toBeNull();
    expect(v.tableDropdown()).toBeNull();
    expect(v.box()).toBeNull();

    v.canvas().onAddExtraTable('Patient', 'dbo.A');
    await v.settle();
    v.dialog.save();
    await v.settle();
    expect(v.savedDestinationObject()).toBe('dbo.A');
  });

  it('MongoDB: no toolbar box; the canvas collection is saved', async () => {
    const v = await mount({ dests: { d1: 'Mongo' }, schema: { d1: () => of({ tables: [] }) } });
    await v.choose('d1');
    expect(v.box()).toBeNull();

    v.canvas().onAddExtraTable('Patient', 'patients');
    await v.settle();
    v.dialog.save();
    await v.settle();
    expect(v.savedDestinationObject()).toBe('patients');
  });

  it('CSV: shows a "File name" box, and what is typed there is saved', async () => {
    const v = await mount({ dests: { d1: 'Csv' }, schema: { d1: () => of({ tables: [] }) } });
    await v.choose('d1');
    expect(v.boxLabel()).toBe('File name');

    await v.typeInBox('patients.csv');
    v.dialog.save();
    await v.settle();
    expect(v.savedDestinationObject()).toBe('patients.csv');
  });

  it('SQL: no box while the table list is loading; a "Table" box once it fails, and Retry brings the picker back', async () => {
    const loading = new Subject<unknown>();
    let calls = 0;
    const v = await mount({ dests: { d1: 'PostgreSql' }, schema: { d1: () => (++calls === 1 ? loading.asObservable() : of({ tables: [table('A')] })) } });
    await v.choose('d1');
    expect(v.box()).toBeNull();

    loading.error(new Error('unreachable'));
    await v.settle();
    expect(v.boxLabel()).toBe('Table');
    await v.typeInBox('dbo.Patients');
    v.dialog.save();
    await v.settle();
    expect(v.savedDestinationObject()).toBe('dbo.Patients');

    v.dialog.retrySchemaLoad();
    await v.settle();
    expect(v.box()).toBeNull();
  });

  it('nothing named anywhere: Save says so and sends nothing', async () => {
    const v = await mount({ dests: { d1: 'Csv' }, schema: { d1: () => of({ tables: [] }) } });
    await v.choose('d1');
    v.dialog.save();
    await v.settle();
    expect(v.create).not.toHaveBeenCalled();
    expect(v.dialog.errorMessage()).toBe('Choose where this mapping writes to first — a table, collection or file name.');
  });

  it('switching the destination from SQL with tables to CSV brings the box in', async () => {
    const v = await mount({ dests: { pg: 'PostgreSql', csv: 'Csv' }, schema: { pg: () => of({ tables: [table('A')] }), csv: () => of({ tables: [] }) } });
    await v.choose('pg');
    expect(v.box()).toBeNull();
    v.dialog.metaForm.controls.destinationId.setValue('csv');
    await v.settle();
    expect(v.boxLabel()).toBe('File name');
  });

  it('editing a CSV profile opens on its saved file name and keeps it', async () => {
    const profile = { id: 'p1', name: 'P', resourceType: 'Patient', sourceConnectionId: 's1', destinationId: 'd1', destinationObject: 'patients.csv', isEnabled: true, fields: [keyField] };
    const v = await mount({ dests: { d1: 'Csv' }, schema: { d1: () => of({ tables: [] }) }, mode: 'edit', profile });
    await v.settle();
    expect(v.box()!.value).toBe('patients.csv');
    v.dialog.save();
    await v.settle();
    expect(v.savedDestinationObject()).toBe('patients.csv');
  });

  it('editing a SQL profile keeps its saved key row exactly as loaded', async () => {
    const profile = { id: 'p1', name: 'P', resourceType: 'Patient', sourceConnectionId: 's1', destinationId: 'd1', destinationObject: 'dbo.A', isEnabled: true, fields: [keyField] };
    const v = await mount({ dests: { d1: 'PostgreSql' }, schema: { d1: () => of({ tables: [table('A')] }) }, mode: 'edit', profile });
    await v.settle();
    const rows = v.dialog.mappingForm()!.rowsRich();
    expect(rows.map(r => `${r.tableName}.${r.targetName}:${r.isUpsertKey}`)).toEqual(['dbo.A.PatientId:true']);
    v.dialog.save();
    await v.settle();
    expect(v.savedDestinationObject()).toBe('dbo.A');
  });

  it('view mode: the box is read-only', async () => {
    const profile = { id: 'p1', name: 'P', resourceType: 'Patient', sourceConnectionId: 's1', destinationId: 'd1', destinationObject: 'patients.csv', isEnabled: true, fields: [keyField] };
    const v = await mount({ dests: { d1: 'Csv' }, schema: { d1: () => of({ tables: [] }) }, mode: 'view', profile });
    await v.settle();
    expect(v.box()!.disabled).toBeTrue();
  });
});
}
