// Step-2 domain/certificate binding for the 3 public-facing apps from an ALREADY-DEPLOYED
// FHIRBridge stack (FHIRBridge app, Demo app, HAPI terminology server) — deployed on its own,
// separately from main.bicep, specifically so binding a domain never requires re-submitting
// main.bicep's full parameter set (sqlSaPassword, jwtSigningKey, redisPassword, image tag, etc.).
// Every property this template doesn't explicitly touch is read back from the live container app
// and passed through unchanged (see custom-domain-app-update.bicep) — so this can't accidentally
// drift env vars, volumes, registries, or existing secrets, the way redeploying the whole
// main.bicep template with a stale parameter value could.
//
// All 3 domain fields are independently OPTIONAL - leave any/all blank to skip that app entirely
// (no read, no write, not even a no-op) this run. Same underlying Azure constraint as main.bicep's
// fhirbridgeAppCustomDomain/etc. — a managed certificate requires the hostname to already be
// registered on the app, so binding a domain is inherently two phases. There is NO bindCertificate
// parameter here — the phase is auto-detected PER APP from the app's own live state: if the domain
// you give isn't already in that app's ingress.customDomains, this run registers the hostname only
// (bindingType Disabled). If it's already there (from a prior run of this same template), this run
// automatically proceeds to create the managed certificate and bind SniEnabled SSL. So the whole
// flow is just "run this template once per app+domain you're setting up, then again after DNS
// propagates" — same template, same inputs, no toggle to get wrong or forget to flip:
//
//   Deploy 1: domain(s) set, not yet registered on the app -> registers the hostname(s) only.
//             Read the `results` output for each app's verification ID and default FQDN — create
//             the CNAME + asuid TXT record at your DNS provider from those, then wait for
//             propagation.
//   Deploy 2: same domain(s), same template, run again -> since the domain(s) now already appear
//             in each app's customDomains, this automatically creates the managed certificate(s)
//             (now that DNS resolves) and binds SniEnabled SSL. If DNS hasn't actually propagated
//             yet, Azure still rejects this with InvalidCustomHostNameValidation - re-run once it
//             has.
//
// Usage (CLI, same command both times):
//   az deployment group create -g <rg> -f custom-domain.bicep \
//     -p namePrefix=segue12 hapiTerminologyDomain=term.example.com
//   # ... create DNS records from the `results` output, wait for propagation, then just re-run the
//   # exact same command - it detects the domain is already registered and binds the certificate.
//
// Or via the Deploy-to-Azure link generated by publish-deploy-artifacts.ps1/.sh (uses
// createUiDefinition.custom-domain.json - each tab shows whether its domain is not yet registered,
// pending certificate binding, or already fully bound). Re-running this template for a second
// domain on the same app is safe — it preserves every other already-bound domain on that app.

@description('The same deployment name prefix used for the original FHIRBridge deployment (e.g. segue12). Used to derive the environment name (<prefix>-env) and all 3 app names.')
param namePrefix string

@description('Custom domain for the FHIRBridge app (e.g. app.example.com). Leave blank to skip this app entirely this run.')
param fhirbridgeAppDomain string = ''

@description('Custom domain for the Demo app. Leave blank to skip this app entirely this run.')
param demoAppDomain string = ''

@description('Custom domain for the HAPI terminology server. Leave blank to skip this app entirely this run.')
param hapiTerminologyDomain string = ''

@description('Region for the (re)deployed container apps + managed certificates. An existing container app\'s own location can\'t be read back at compile time (Bicep BCP120), so this must match wherever the environment/apps actually live — defaults to the resource group\'s region, which is what main.bicep itself uses.')
param location string = resourceGroup().location

// Only the module needs an actual reference to the environment (to parent the managed
// certificate) - this template only ever needs its name, to derive app names alongside.
var environmentName = '${namePrefix}-env'

// Every app this template COULD touch, with its computed name and the domain the caller gave it.
// Filtered down to just the ones actually requested this run — an app with an empty domain gets no
// resource read, no resource write, not even a no-op deployment operation for it.
var allAppConfigs = [
  { key: 'fhirbridgeApp', name: '${namePrefix}-app', domain: fhirbridgeAppDomain }
  { key: 'demoApp', name: '${namePrefix}-demo-app', domain: demoAppDomain }
  { key: 'hapiTerminology', name: '${namePrefix}-term', domain: hapiTerminologyDomain }
]
var activeAppConfigs = filter(allAppConfigs, c => !empty(c.domain))

resource apps 'Microsoft.App/containerApps@2024-03-01' existing = [for c in activeAppConfigs: {
  name: c.name
}]

// Writing the updated containerApp directly in THIS template (same resource type + name as the
// `apps` existing reference above) would compile to an ARM resource whose own PUT body contains a
// reference()/listSecrets() call against itself - a genuine self-referencing circular dependency
// ARM's template validator rejects at deploy time (this doesn't show up under `az deployment group
// what-if`, which reads the live resource directly rather than running the same pre-deploy
// dependency-cycle check a real deployment does). The managed certificate ALSO can't be created
// here as a conditional resource keyed off the app's live customDomains — a resource `if` condition
// can only reference plain parameters/variables, never another resource's live properties (Bicep
// BCP177). Both the write and the certificate live in the custom-domain-app-update.bicep module
// instead: every value derived from `apps` is fully resolved here (as deployment-time module
// parameters, NOT a top-level `var`, which would hit BCP182) and handed in as plain values,
// including the already-resolved `bindCertificate` boolean the module's own conditional needs.
module appUpdates 'custom-domain-app-update.bicep' = [for (c, i) in activeAppConfigs: {
  name: 'update-${c.name}-customdomain'
  params: {
    appName: c.name
    location: location
    environmentName: environmentName
    managedEnvironmentId: apps[i].properties.managedEnvironmentId
    domain: c.domain
    // Per-app phase auto-detection: was THIS domain already registered on THIS app by a prior run
    // of this template? If so, THIS run's job is to bind the certificate; otherwise it's to
    // register the hostname only.
    bindCertificate: contains(map(apps[i].properties.configuration.ingress.?customDomains ?? [], cd => cd.name), c.domain)
    baseConfiguration: apps[i].properties.configuration
    // Container Apps' listSecrets action returns actual secret VALUES (unlike a plain GET/
    // `existing` reference, which redacts them to name-only) — needed because redeploying a
    // containerApp resource with a properties.configuration.secrets array missing `value` would
    // blank out every existing secret (registry password, DB passwords, etc.), breaking the app.
    existingSecrets: apps[i].listSecrets().value
    // Drop any prior entry for this same domain (idempotent re-run) — every OTHER already-bound
    // domain on this app is left untouched.
    otherCustomDomains: filter(apps[i].properties.configuration.ingress.?customDomains ?? [], cd => cd.name != c.domain)
    containerTemplate: apps[i].properties.template
  }
}]

output results array = [for (c, i) in activeAppConfigs: {
  app: c.key
  appName: c.name
  domain: c.domain
  appFqdn: apps[i].properties.configuration.ingress.fqdn
  domainVerificationId: apps[i].properties.customDomainVerificationId
  customDomainUrl: 'https://${c.domain}'
  phase: contains(map(apps[i].properties.configuration.ingress.?customDomains ?? [], cd => cd.name), c.domain) ? 'certificate-bound' : 'hostname-registered-create-dns-then-redeploy-to-bind-certificate'
}]
