// Step-2 domain/certificate binding for the Segue app from an ALREADY-DEPLOYED
// Segue stack — deployed on its own, separately from main.bicep,
// specifically so binding a domain never requires re-submitting main.bicep's full parameter set
// (postgresPassword, jwtSigningKey, redisPassword, image tag, etc.). Every property this template
// doesn't explicitly touch is read back from the live container app and passed through unchanged
// (see custom-domain-app-update.bicep) — so this can't accidentally drift env vars, volumes,
// registries, or existing secrets, the way redeploying the whole main.bicep template with a stale
// parameter value could.
//
// The domain field is OPTIONAL - leave it blank to skip this app entirely (no read, no write, not
// even a no-op) this run.
//
// ONE deploy does the WHOLE thing for the domain you set — register the hostname, create the
// managed certificate, and bind it — sequenced internally (two module calls, the second
// depending on the first) so Azure always sees "hostname added" before "certificate created" and
// "certificate created" before "certificate bound", exactly the order its API requires. The
// PREREQUISITE this template does NOT do for you: the CNAME + asuid TXT records must already exist
// and have propagated BEFORE you run this — Azure validates DNS at the hostname-registration step
// itself, not just at certificate-creation, so there's no way around having DNS ready first no
// matter how this template is structured. But you don't need a throwaway first deploy to find out
// the verification ID to put in that TXT record: main.bicep's own output
// (segueAppDomainVerificationId) already exposes it
// unconditionally, the moment the app exists — no domain needs to have been set on that first
// deploy at all.
//
// So the real flow is:
//   1. Deploy main.bicep (Step 1) — no domain field needed.
//   2. Read the verification ID + default FQDN from main.bicep's
//      outputs (or `az containerapp show`, or containerization/scripts/discover-custom-domains.ps1|sh).
//   3. Create the CNAME + asuid TXT record at your DNS provider yourself. Wait for propagation.
//   4. Deploy THIS template, once, with the domain you set up DNS for. It registers the
//      hostname, creates the certificate, and binds it — all in this one deploy.
//
// If DNS isn't actually ready yet when you run step 4, Azure rejects it with
// InvalidCustomHostNameValidation (TXT record not found) at the hostname-registration step — just
// wait and re-run once it resolves; re-running is always safe (idempotent either way).
//
// Usage:
//   az deployment group create -g <rg> -f custom-domain.bicep \
//     -p namePrefix=segue12 segueAppDomain=app.example.com
//
// Or via the Deploy-to-Azure link generated by publish-deploy-artifacts.ps1/.sh (uses
// createUiDefinition.custom-domain.json). Re-running this template for a second domain on the
// same app, or re-running it at all, is safe — it preserves every other already-bound domain on
// that app and is a no-op for a domain that's already fully bound.
//
// containerization/scripts/auto-bind-custom-domain.ps1|sh automates steps 2-4 above end to end
// (reads the verification ID directly from the live app, prints the DNS records, polls DNS itself,
// then runs this deploy) if you'd rather not do the DNS wait manually.

@description('The same deployment name prefix used for the original Segue deployment (e.g. segue12). Used to derive the environment name (<prefix>-env) and the app name.')
param namePrefix string

@description('Custom domain for the Segue app (e.g. app.example.com). Leave blank to skip this app entirely this run. Its CNAME + asuid TXT records must already be created and propagated BEFORE this deploy - see main.bicep\'s segueAppDomainVerificationId output for the TXT value.')
param segueAppDomain string = ''

@description('Region for the (re)deployed container app + managed certificate. An existing container app\'s own location can\'t be read back at compile time (Bicep BCP120), so this must match wherever the environment/app actually lives — defaults to the resource group\'s region, which is what main.bicep itself uses.')
param location string = resourceGroup().location

@description('MUST match whatever enableFrontDoorWaf was set to on the original main.bicep deployment for this namePrefix — this template has no way to detect that on its own. false (default) binds the domain directly to the Container App, exactly as this template always has. true instead binds it to Front Door\'s endpoint (skipping the Container App binding entirely — Front Door reaches the app using its own default hostname, so the app never needs the custom domain registered on it), so traffic through the domain actually passes through the WAF instead of bypassing it. Passing true when Front Door was never actually enabled fails outright — the Front Door resources this template then tries to read simply won\'t exist.')
param enableFrontDoorWaf bool = false

// Only the module needs an actual reference to the environment (to parent the managed
// certificate) - this template only ever needs its name, to derive the app name alongside.
var environmentName = '${namePrefix}-env'

// The app this template touches, with its computed name and the domain the caller gave it.
// Filtered down to just this entry if it was actually requested this run — an empty domain gets no
// resource read, no resource write, not even a no-op deployment operation for it. Empty entirely
// when enableFrontDoorWaf is true — that path is handled by the Front Door resources below instead.
var allAppConfigs = [
  { key: 'segueApp', name: '${namePrefix}-app', domain: segueAppDomain }
]
var activeAppConfigs = enableFrontDoorWaf ? [] : filter(allAppConfigs, c => !empty(c.domain))

resource apps 'Microsoft.App/containerApps@2024-03-01' existing = [for c in activeAppConfigs: {
  name: c.name
}]

// Writing the updated containerApp directly in THIS template (same resource type + name as the
// `apps` existing reference above) would compile to an ARM resource whose own PUT body contains a
// reference()/listSecrets() call against itself - a genuine self-referencing circular dependency
// ARM's template validator rejects at deploy time (this doesn't show up under `az deployment group
// what-if`, which reads the live resource directly rather than running the same pre-deploy
// dependency-cycle check a real deployment does). The managed certificate ALSO can't be created
// here as a conditional resource keyed off the app's live customDomains — a resource `if` condition
// can only reference plain parameters/variables, never another resource's live properties (Bicep
// BCP177). Both the write and the certificate live in the custom-domain-app-update.bicep module
// instead: every value derived from `apps` is fully resolved here (as deployment-time module
// parameters, NOT a top-level `var`, which would hit BCP182) and handed in as plain values,
// including the already-resolved `bindCertificate` boolean the module's own conditional needs.
//
// Two module calls per app, not one: `registerHostnames` (bindCertificate: false) always runs
// first; `bindCertificates` (bindCertificate: true) explicitly depends on it via `dependsOn`, so
// Azure only ever sees "create certificate" after "hostname added" has actually completed - the
// exact order its API enforces (RequireCustomHostnameInEnvironment otherwise). `otherCustomDomains`
// /`baseConfiguration`/`containerTemplate` are safe to compute identically for both calls: neither
// phase touches any OTHER domain, registries, secrets shape, or the container template itself, so
// there's nothing that differs between "read once up front" and "re-read after phase one" for
// those particular fields - only `bindCertificate` (a plain, non-derived input) and `cert.id`
// (a normal data dependency once the certificate resource exists) actually change between the two
// calls.
module registerHostnames 'custom-domain-app-update.bicep' = [for (c, i) in activeAppConfigs: {
  name: 'register-${c.name}-customdomain'
  params: {
    appName: c.name
    location: location
    environmentName: environmentName
    managedEnvironmentId: apps[i].properties.managedEnvironmentId
    domain: c.domain
    bindCertificate: false
    baseConfiguration: apps[i].properties.configuration
    // Container Apps' listSecrets action returns actual secret VALUES (unlike a plain GET/
    // `existing` reference, which redacts them to name-only) — needed because redeploying a
    // containerApp resource with a properties.configuration.secrets array missing `value` would
    // blank out every existing secret (registry password, DB passwords, etc.), breaking the app.
    existingSecrets: apps[i].listSecrets().value
    // Drop any prior entry for this same domain (idempotent re-run) — every OTHER already-bound
    // domain on this app is left untouched.
    otherCustomDomains: filter(apps[i].properties.configuration.ingress.?customDomains ?? [], cd => cd.name != c.domain)
    containerTemplate: apps[i].properties.template
  }
}]

module bindCertificates 'custom-domain-app-update.bicep' = [for (c, i) in activeAppConfigs: {
  name: 'bind-${c.name}-customdomain'
  params: {
    appName: c.name
    location: location
    environmentName: environmentName
    managedEnvironmentId: apps[i].properties.managedEnvironmentId
    domain: c.domain
    bindCertificate: true
    baseConfiguration: apps[i].properties.configuration
    existingSecrets: apps[i].listSecrets().value
    otherCustomDomains: filter(apps[i].properties.configuration.ingress.?customDomains ?? [], cd => cd.name != c.domain)
    containerTemplate: apps[i].properties.template
  }
  dependsOn: [registerHostnames]
}]

output results array = [for (c, i) in activeAppConfigs: {
  app: c.key
  appName: c.name
  domain: c.domain
  appFqdn: apps[i].properties.configuration.ingress.fqdn
  domainVerificationId: apps[i].properties.customDomainVerificationId
  customDomainUrl: 'https://${c.domain}'
}]

// --- Front Door path — only when enableFrontDoorWaf is true. Resource names recomputed the same
//     deterministic way main.bicep generated them (uniqueString(resourceGroup().id, namePrefix) is
//     a pure function of inputs already known here), so nothing needs to be plumbed from that
//     deployment's outputs to find the right Front Door profile/endpoint/route/policy to attach to.
//
//     Unlike the Container-App-direct path above, creating the domain AND associating it with the
//     route/WAF policy can happen in this SAME deploy: AFDX domain validation runs asynchronously
//     in the background once the _dnsauth TXT record exists — it does not block these resources
//     from being created first the way Container Apps' RequireCustomHostnameInEnvironment does. The
//     domain just won't actually serve traffic correctly (TLS handshake fails) until validation
//     completes and Azure auto-issues the managed certificate — both happen on their own, no further
//     deployment needed once the TXT record is in place. So there is no bindCustomDomainCertificates
//     equivalent on this path — one deploy is genuinely enough. NOT LIVE-TESTED (unlike the
//     Container-App-direct path above, which has real deploy history behind it) — validate this
//     against a real subscription before relying on it.

var uniqueSuffix = uniqueString(resourceGroup().id, namePrefix)
var frontDoorEndpointName = toLower('${namePrefix}-${take(uniqueSuffix, 8)}')
var frontDoorProfileName = '${namePrefix}-afd'
var frontDoorRouteName = '${namePrefix}-app-route'
var frontDoorSecurityPolicyName = '${namePrefix}-app-security-policy'

resource frontDoorProfile 'Microsoft.Cdn/profiles@2024-02-01' existing = if (enableFrontDoorWaf) {
  name: frontDoorProfileName
}

resource frontDoorEndpoint 'Microsoft.Cdn/profiles/afdEndpoints@2024-02-01' existing = if (enableFrontDoorWaf) {
  parent: frontDoorProfile
  name: frontDoorEndpointName
}

resource frontDoorRoute 'Microsoft.Cdn/profiles/afdEndpoints/routes@2024-02-01' existing = if (enableFrontDoorWaf) {
  parent: frontDoorEndpoint
  name: frontDoorRouteName
}

resource frontDoorSecurityPolicy 'Microsoft.Cdn/profiles/securityPolicies@2024-02-01' existing = if (enableFrontDoorWaf) {
  parent: frontDoorProfile
  name: frontDoorSecurityPolicyName
}

// ManagedCertificate can be requested immediately — it just won't actually issue until the
// _dnsauth TXT record validates, same "requested now, materializes once DNS is ready" pattern as
// the Container Apps managed certificate above, minus that path's hard ordering requirement.
resource frontDoorCustomDomain 'Microsoft.Cdn/profiles/customDomains@2024-02-01' = if (enableFrontDoorWaf && !empty(segueAppDomain)) {
  parent: frontDoorProfile
  name: replace(segueAppDomain, '.', '-')
  properties: {
    hostName: segueAppDomain
    tlsSettings: {
      certificateType: 'ManagedCertificate'
    }
  }
}

// Same circular-dependency restriction as the Container App path — writing the route/security
// policy using values read from those SAME resources (via the `existing` references above) in this
// same template would self-reference. The write lives in its own module instead; see
// custom-domain-frontdoor-update.bicep's own header comment for the details.
module frontDoorRouteAndWafUpdate 'custom-domain-frontdoor-update.bicep' = if (enableFrontDoorWaf && !empty(segueAppDomain)) {
  name: 'frontdoor-route-waf-customdomain-update'
  params: {
    profileName: frontDoorProfileName
    endpointName: frontDoorEndpointName
    routeName: frontDoorRouteName
    securityPolicyName: frontDoorSecurityPolicyName
    newCustomDomainId: frontDoorCustomDomain.id
    existingRouteProperties: frontDoorRoute.properties
    existingSecurityPolicyParameters: frontDoorSecurityPolicy.properties.parameters
  }
}

@description('Populated only when enableFrontDoorWaf is true and segueAppDomain is set. A Front Door-specific validation token — different from segueAppDomainVerificationId\'s asuid.<domain> mechanism, which only applies to the Container-App-direct path. Add a TXT record at _dnsauth.<your domain> with this value; Azure auto-detects it and issues the managed certificate once found — no further deployment needed.')
output frontDoorCustomDomainValidationToken string = (enableFrontDoorWaf && !empty(segueAppDomain)) ? frontDoorCustomDomain.properties.validationProperties.validationToken : ''

output frontDoorCustomDomainUrl string = (enableFrontDoorWaf && !empty(segueAppDomain)) ? 'https://${segueAppDomain}' : ''
