using FHIRBridge.Domain.Enums;

namespace FHIRBridge.Application.DTOs;

public sealed record DestinationSchemaDto(
    Guid DestinationId,
    IReadOnlyList<DestinationTableSchemaDto> Tables);

/// <summary>
/// Ad-hoc connection details for a not-yet-saved destination, used by the builder to test the connection
/// and load real tables/columns. Either supply <see cref="ConnectionString"/> directly, or the discrete
/// server/database/auth fields (SQL Server / Azure SQL). No secret is persisted.
/// </summary>
public sealed record DestinationConnectionProbeRequest(
    DestinationType DestinationType,
    string? Server = null,
    string? Database = null,
    string? Authentication = null,
    string? Username = null,
    string? Password = null,
    bool TrustServerCertificate = true,
    bool Encrypt = true,
    string? ConnectionString = null,
    // PostgreSQL / MySQL only: unlike SQL Server (which always negotiates an encrypted TDS handshake even
    // against a plain server), these providers refuse to connect at all if SSL is required but the server
    // doesn't offer it — so this must default false to keep working against local/docker instances with SSL
    // off, and be explicitly opted into for providers that enforce it (e.g. AWS RDS's rds.force_ssl).
    bool RequireSsl = false,
    // Set when this probe is forking from an already-saved destination (picked "Existing" in the wizard, then
    // some other field like RequireSsl edited) and Password was left blank — lets the service inherit that
    // destination's stored password the same way AddDestinationConfigurationAsync does at save time, so testing
    // a connection doesn't require retyping a password the user never meant to change.
    Guid? ExistingDestinationId = null);

/// <summary>Result of a connection probe: whether it connected, any error, and the introspected tables.</summary>
public sealed record DestinationSchemaProbeDto(
    bool Connected,
    string? Error,
    IReadOnlyList<DestinationTableSchemaDto> Tables);

public sealed record DestinationTableSchemaDto(
    string SchemaName,
    string TableName,
    string FullName,
    IReadOnlyList<DestinationColumnSchemaDto> Columns);

public sealed record DestinationColumnSchemaDto(
    string Name,
    string DataType,
    string MappingValueType,
    bool IsNullable,
    int? MaxLength,
    bool IsPrimaryKey = false,
    bool IsUnique = false,
    // True for identity/auto-increment/computed columns — the database generates their value, so they can never
    // be a write target (nor a usable upsert key). The mapping UI must not offer them as mappable columns.
    bool IsAutoGenerated = false,
    // Total significant digits and digits right of the decimal point for a numeric/decimal column — null for
    // non-numeric types and for types (float/real/money) where the underlying driver doesn't report either.
    // Used to reject a mapped value that would overflow the column before it's ever sent to the destination.
    int? NumericPrecision = null,
    int? NumericScale = null,
    bool IsForeignKey = false,
    string? References = null);

/// <summary>
/// Adds one column to an already-existing destination table via a real ALTER TABLE — SQL Server /
/// Azure SQL only. Same ad-hoc connection model as <see cref="DestinationConnectionProbeRequest"/>;
/// no secret persisted. <see cref="TableName"/> may be schema-qualified ("dbo.Patient") or bare.
/// </summary>
public sealed record AddColumnRequest(
    DestinationConnectionProbeRequest Connection,
    string TableName,
    string ColumnName,
    string DataType,
    bool IsNullable = true);

/// <summary>One user-specified column for <see cref="CreateTableRequest"/> — a name plus a data type string
/// in the same allowed shapes AddColumnRequest.DataType accepts (fixed keyword, sized string, or decimal(p,s)).</summary>
public sealed record TableColumnDefinition(string Name, string DataType);

/// <summary>
/// Creates a new destination table (SQL Server / Azure SQL only). Always gets an auto-increment
/// <c>Id</c> primary key first, followed by any <see cref="Columns"/>. Optionally makes it a child of an
/// already-existing table: supplying <see cref="ParentTable"/> adds a BIGINT <see cref="ForeignKeyColumnName"/>
/// column (defaults to "{ParentTableName}Id") with a FOREIGN KEY REFERENCES constraint against
/// <see cref="ParentTable"/>.<see cref="ParentColumn"/> (defaults to "Id"). Fails if the table already
/// exists, or if a requested parent table doesn't, rather than silently no-op'ing.
/// </summary>
public sealed record CreateTableRequest(
    DestinationConnectionProbeRequest Connection,
    string TableName,
    IReadOnlyList<TableColumnDefinition>? Columns = null,
    string? ParentTable = null,
    string? ParentColumn = null,
    string? ForeignKeyColumnName = null);

/// <summary>
/// Permanently drops one column from an already-existing destination table via a real
/// <c>ALTER TABLE ... DROP COLUMN</c> — SQL Server / Azure SQL only. Unlike <see cref="AddColumnRequest"/>/
/// <see cref="CreateTableRequest"/>, this is destructive and irreversible: any data in that column is
/// gone. The caller (the mapping canvas) is responsible for confirming this with the user first — this
/// service executes it unconditionally once called.
/// </summary>
public sealed record DropColumnRequest(
    DestinationConnectionProbeRequest Connection,
    string TableName,
    string ColumnName);

/// <summary>
/// Changes an already-existing column's data type via a real <c>ALTER TABLE ... ALTER COLUMN</c>, and
/// optionally renames it via <c>sp_rename</c> (only when <see cref="NewColumnName"/> differs from
/// <see cref="ColumnName"/>) — SQL Server / Azure SQL only. The column's existing NULL/NOT NULL
/// constraint is always preserved (the generated ALTER COLUMN statement omits NULL/NOT NULL, which SQL
/// Server keeps unchanged when left unspecified). Fails (does not throw) if the new type is incompatible
/// with existing data, the new name collides with another column, etc.
/// </summary>
public sealed record AlterColumnRequest(
    DestinationConnectionProbeRequest Connection,
    string TableName,
    string ColumnName,
    string NewDataType,
    string? NewColumnName = null);

/// <summary>Result of a schema-mutating action. <see cref="Column"/> is populated by AddColumnAsync (the one
/// column added); <see cref="Table"/> by CreateTableAsync (the full created table, all columns including the
/// FK if any) — so the caller never needs a second round trip to know the table's real shape. AddColumnAsync
/// also populates <see cref="Table"/>, but only when its target table didn't already exist and had to be
/// auto-created (Id + this one column) — the caller has no prior record of that table at all otherwise.
/// <see cref="AlreadyExisted"/> is set only by CreateTableAsync, when the requested table turned out to
/// already exist for real by the time the (deferred, queued) create actually ran — see its own doc comment
/// for why this is a success, not a failure, with <see cref="Table"/> carrying the table's real current
/// shape rather than whatever was originally requested.</summary>
public sealed record SchemaMutationResultDto(
    bool Success,
    string? Error,
    DestinationColumnSchemaDto? Column = null,
    DestinationTableSchemaDto? Table = null,
    bool AlreadyExisted = false);
