<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FHIRBridge.Worker-6f91fba1-eb4e-48af-85ee-5f25d0690c6d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.12" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="System.Threading.AccessControl" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Consumers\" />
    <Folder Include="BackgroundServices\" />
    <Folder Include="Processors\" />
    <Folder Include="Schedulers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FHIRBridge.Application\FHIRBridge.Application.csproj" />
    <ProjectReference Include="..\..\FHIRBridge.Infrastructure\FHIRBridge.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Runtime\FHIRBridge.Runtime.Application\FHIRBridge.Runtime.Application.csproj" />
    <ProjectReference Include="..\..\Runtime\FHIRBridge.Runtime.Infrastructure\FHIRBridge.Runtime.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\FHIRBridge.Observability\FHIRBridge.Observability.csproj" />
    <ProjectReference Include="..\..\FHIRBridge.Infrastructure.Migrations.PostgreSql\FHIRBridge.Infrastructure.Migrations.PostgreSql.csproj" />
  </ItemGroup>
</Project>
