import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { DESTINATION_ENDPOINTS } from '../core/api-endpoints';

export interface DestinationColumn {
  name: string;
  dataType: string;
  mappingValueType: string;
  isNullable: boolean;
  maxLength: number | null;
  /** Read from the live destination's real key constraints (SQL Server / Azure SQL only) — never guessed
   *  from the column's name. Absent/false for PostgreSQL/MySQL columns, which have no such lookup. */
  isPrimaryKey?: boolean;
  isUnique?: boolean;
  // Identity/auto-increment/computed column — the database generates its value, so it can never be a mapping
  // target or upsert key. Filtered out of the column pickers.
  isAutoGenerated?: boolean;
  isForeignKey?: boolean;
  /** Set only when isForeignKey — "{schema}.{table}.{column}" of the referenced primary key. */
  references?: string | null;
  /** Absent (e.g. every real probe() response) is treated as 'probed'. Only the mapping-canvas's own
   *  "+ Add column" flow ever stamps 'userCreated', client-side — the backend never sets this. */
  origin?: 'probed' | 'userCreated';
}

export interface DestinationTable {
  schemaName: string;
  tableName: string;
  fullName: string;
  columns: DestinationColumn[];
  /** Same convention as DestinationColumn.origin — stamped only by the "+ Add a table" flow. */
  origin?: 'probed' | 'userCreated';
}

export interface DestinationSchemaProbe {
  connected: boolean;
  error: string | null;
  tables: DestinationTable[];
}

export interface DestinationProbeRequest {
  destinationType: string;
  server?: string;
  database?: string;
  authentication?: string;
  username?: string;
  password?: string;
  trustServerCertificate?: boolean;
  encrypt?: boolean;
  connectionString?: string;
  // PostgreSQL / MySQL only — see DestinationConnectionProbeRequest.RequireSsl on the backend for why this
  // defaults false rather than being hardcoded true like SQL Server's trustServerCertificate/encrypt above.
  requireSsl?: boolean;
  // Set when forking from an already-saved destination with the password left blank — lets the backend
  // inherit that destination's stored password (see DestinationConnectionProbeRequest.ExistingDestinationId).
  existingDestinationId?: string | null;
}

export interface SchemaMutationResult {
  success: boolean;
  error: string | null;
  column: DestinationColumn | null;
  /** Populated by createTable() — the full created table (Id + any requested columns + the FK column, if
   *  any). Also populated by addColumn() when its target table didn't already exist and had to be
   *  auto-created (Id + the one added column) — the caller otherwise has no prior record of that table. */
  table: DestinationTable | null;
  /** Set only by createTable(), only when the requested table turned out to already exist for real by the
   *  time this (deferred, queued) create actually ran — success, not failure, with `table` carrying its
   *  real current shape rather than whatever columns were originally requested. See
   *  SqlDestinationSchemaService.CreateTableAsync's own doc comment for why this must never be a hard
   *  failure — a dependent queued addColumn() behind it would otherwise be stranded. */
  alreadyExisted?: boolean;
}

/** One user-specified column for CreateTableRequest — name + a data type in the same shapes the
 *  add-column modal already offers (fixed keyword, sized string, or decimal(p,s)). */
export interface TableColumnDefinition {
  name: string;
  dataType: string;
}

export interface AddColumnRequest {
  connection: DestinationProbeRequest;
  tableName: string;
  columnName: string;
  dataType: string;
  isNullable?: boolean;
}

export interface CreateTableRequest {
  connection: DestinationProbeRequest;
  tableName: string;
  columns?: TableColumnDefinition[];
  /** Supplying this makes the new table a child: adds a BIGINT FK column referencing parentTable.parentColumn. */
  parentTable?: string;
  /** Defaults server-side to "Id" when parentTable is set. */
  parentColumn?: string;
  /** Defaults server-side to "{parentTableName}Id" when parentTable is set. */
  foreignKeyColumnName?: string;
}

/** Permanently drops a column via a real ALTER TABLE ... DROP COLUMN — irreversible, data included. */
export interface DropColumnRequest {
  connection: DestinationProbeRequest;
  tableName: string;
  columnName: string;
}

/** Changes an existing column's data type via a real ALTER TABLE ... ALTER COLUMN, and optionally
 *  renames it (via sp_rename) when newColumnName differs from columnName. The column's existing
 *  NULL/NOT NULL constraint is always preserved server-side. */
export interface AlterColumnRequest {
  connection: DestinationProbeRequest;
  tableName: string;
  columnName: string;
  newDataType: string;
  newColumnName?: string;
}

export interface SftpConnectionTestRequest {
  host: string;
  port: number;
  username: string;
  password?: string;
  remoteFolder?: string;
  /** When re-testing an already-saved destination without retyping its password, carries the destination's id
   *  so the backend can resolve the stored password instead. */
  destinationId?: string;
}

// No tokenEndpoint — for "oauth2"/"clientcredentials" it's discovered server-side from baseUrl via
// GET {baseUrl}/.well-known/smart-configuration (see FhirDestinationConnectionTestService.DiscoverTokenEndpointAsync)
// rather than typed by the user.
export interface FhirConnectionTestRequest {
  baseUrl: string;
  authType: string;
  clientId?: string;
  clientSecret?: string;
  username?: string;
  password?: string;
  bearerToken?: string;
  // Azure FHIR Service only — when tenantId is supplied the backend computes the Entra ID token endpoint
  // directly instead of discovering it from a SMART configuration document (see FhirConnectionTestRequest.cs).
  tenantId?: string;
  scope?: string;
  managedIdentityClientId?: string;
  authorityHost?: string;
  /** When re-testing an already-saved destination without retyping its secret (clientSecret/password/
   *  bearerToken left blank — "Leave blank to keep the current X"), carries the destination's id so the backend
   *  can resolve the stored one instead. Mirrors MongoConnectionTestRequest.destinationId/
   *  BlobConnectionTestRequest.destinationId. */
  destinationId?: string;
}

export interface ConnectionTestResult {
  connected: boolean;
  error: string | null;
}

// Medplum connection test — credentials come straight off the form (nothing saved yet). authMethod is
// 'client_secret' (default) or 'private_key_jwt', in which case `secret` carries the PEM private key.
export interface MedplumConnectionTestRequest {
  baseUrl: string;
  clientId: string;
  secret: string;
  authMethod?: string;
  keyId?: string;
  tokenUrl?: string;
}

// Mongo connection test — the whole connection string is the credential (must embed the database name).
export interface MongoConnectionTestRequest {
  connectionString: string;
  /** When supplied, the test also checks whether this collection exists (not just connectivity). */
  collection?: string;
  /** Mirrors the form's "Create collection if not exists" checkbox — skips the missing-collection failure. */
  createIfNotExists?: boolean;
  /** When re-testing an already-saved destination without retyping its connection string, carries the
   *  destination's id so the backend can resolve the stored one instead. */
  destinationId?: string;
}

export interface MongoConnectionTestResult extends ConnectionTestResult {
  /** The database's real collection names, returned on every successful connect — lets the form offer them
   *  as an autocomplete instead of requiring the collection name to be typed blind. */
  collections?: string[];
}

// Azure Blob connection test — split auth fields (no metadata blob). `secret` is the connection string /
// account key / SAS / service-principal client secret per authMode; omitted for managedIdentity.
export interface BlobConnectionTestRequest {
  authMode: string;
  container: string;
  secret?: string;
  accountUrl?: string;
  accountName?: string;
  endpointSuffix?: string;
  tenantId?: string;
  clientId?: string;
  managedIdentityClientId?: string;
  /** When re-testing an already-saved destination without retyping its secret, carries the destination's id so
   *  the backend can resolve the stored one instead. */
  destinationId?: string;
}

export interface FabricConnectionTestRequest {
  /** "oneLakeFiles" or "warehouseTable" — decides which endpoints the backend probes. */
  mode: string;
  authMode: string;
  workspace: string;
  itemName: string;
  itemType?: string;
  secret?: string;
  tenantId?: string;
  clientId?: string;
  managedIdentityClientId?: string;
  endpointSuffix?: string;
  authorityHost?: string;
  accountUrl?: string;
  warehouseSqlEndpoint?: string;
  warehouseStagingLakehouse?: string;
  /** When re-testing an already-saved destination without retyping its secret, carries the destination's id so
   *  the backend can resolve the stored one instead. */
  destinationId?: string;
}

/**
 * Fabric test result. Reports OneLake and the Warehouse endpoint separately because they authenticate against
 * different token audiences and fail independently — a single pass/fail hides which half is misconfigured.
 */
export interface FabricConnectionTestResult extends ConnectionTestResult {
  oneLakeReachable: boolean;
  /** Null when the landing mode never touches the Warehouse endpoint. */
  warehouseReachable: boolean | null;
  /** Set when the identity authenticated but was refused — names the Fabric workspace role to grant. */
  permissionHint: string | null;
}

/** FHIR-specific test result — adds the discovered token endpoint so the wizard can persist it into the
 *  (now-hidden) tokenEndpoint form control exactly as if the user had typed it in. */
export interface FhirConnectionTestResult extends ConnectionTestResult {
  resolvedTokenEndpoint: string | null;
}

/**
 * Tests a relational destination connection and loads its tables/columns for the pipeline builder's
 * table/column pickers. Backed by POST /api/v1/destinations/schema-preview (auth token attached by the
 * global auth interceptor).
 */
@Injectable({ providedIn: 'root' })
export class DestinationSchemaService {
  private readonly http = inject(HttpClient);

  probe(request: DestinationProbeRequest): Observable<DestinationSchemaProbe> {
    return this.http.post<DestinationSchemaProbe>(DESTINATION_ENDPOINTS.schemaPreview, request);
  }

  /** Tables/columns of an already-saved relational destination, introspected server-side using its stored
   *  secret — no credentials round-trip through the browser. Returns an empty table list (not an error) for
   *  a non-relational destination type. */
  getSchema(destinationId: string): Observable<{ destinationId: string; tables: DestinationTable[] }> {
    return this.http.get<{ destinationId: string; tables: DestinationTable[] }>(DESTINATION_ENDPOINTS.schema(destinationId));
  }

  addColumn(request: AddColumnRequest): Observable<SchemaMutationResult> {
    return this.http.post<SchemaMutationResult>(DESTINATION_ENDPOINTS.addColumn, request);
  }

  createTable(request: CreateTableRequest): Observable<SchemaMutationResult> {
    return this.http.post<SchemaMutationResult>(DESTINATION_ENDPOINTS.createTable, request);
  }

  dropColumn(request: DropColumnRequest): Observable<SchemaMutationResult> {
    return this.http.post<SchemaMutationResult>(DESTINATION_ENDPOINTS.dropColumn, request);
  }

  alterColumn(request: AlterColumnRequest): Observable<SchemaMutationResult> {
    return this.http.post<SchemaMutationResult>(DESTINATION_ENDPOINTS.alterColumn, request);
  }

  /** Tests an ad-hoc SFTP connection for a CSV destination (storageType 'sftp'). */
  testSftp(request: SftpConnectionTestRequest): Observable<ConnectionTestResult> {
    return this.http.post<ConnectionTestResult>(DESTINATION_ENDPOINTS.sftpTest, request);
  }

  /** Tests an ad-hoc FHIR-repository connection (e.g. Aidbox) for a not-yet-saved FhirRepository destination. */
  testFhir(request: FhirConnectionTestRequest): Observable<FhirConnectionTestResult> {
    return this.http.post<FhirConnectionTestResult>(DESTINATION_ENDPOINTS.fhirTest, request);
  }

  /** Tests an ad-hoc Medplum connection for a not-yet-saved Medplum destination — mints an OAuth2 token from
   *  the supplied credentials and pings {baseUrl}/metadata server-side. */
  testMedplum(request: MedplumConnectionTestRequest): Observable<ConnectionTestResult> {
    return this.http.post<ConnectionTestResult>(DESTINATION_ENDPOINTS.medplumTest, request);
  }

  /** Tests an ad-hoc MongoDB connection for a not-yet-saved Mongo destination — opens a client on the
   *  connection string, runs a ping server-side, and (on success) returns the database's real collection names. */
  testMongo(request: MongoConnectionTestRequest): Observable<MongoConnectionTestResult> {
    return this.http.post<MongoConnectionTestResult>(DESTINATION_ENDPOINTS.mongoTest, request);
  }

  /** Tests an ad-hoc Azure Blob Storage connection for a not-yet-saved Blob destination — builds the container
   *  client for the auth mode and does a reachability round-trip server-side. */
  testBlob(request: BlobConnectionTestRequest): Observable<ConnectionTestResult> {
    return this.http.post<ConnectionTestResult>(DESTINATION_ENDPOINTS.blobTest, request);
  }

  /**
   * Tests a Microsoft Fabric connection. The result is richer than the shared ConnectionTestResult because
   * Fabric has two endpoints that fail independently (OneLake, and a Warehouse TDS endpoint) using different
   * token audiences — reporting them apart is what makes a failure actionable.
   */
  testFabric(request: FabricConnectionTestRequest): Observable<FabricConnectionTestResult> {
    return this.http.post<FabricConnectionTestResult>(DESTINATION_ENDPOINTS.fabricTest, request);
  }
}
