import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { DESTINATION_ENDPOINTS } from '../core/api-endpoints';

export interface DestinationColumn {
  name: string;
  dataType: string;
  mappingValueType: string;
  isNullable: boolean;
  maxLength: number | null;
  isPrimaryKey?: boolean;
  isUnique?: boolean;
  // Identity/auto-increment/computed column — the database generates its value, so it can never be a mapping
  // target or upsert key. Filtered out of the column pickers.
  isAutoGenerated?: boolean;
}

export interface DestinationTable {
  schemaName: string;
  tableName: string;
  fullName: string;
  columns: DestinationColumn[];
}

export interface DestinationSchemaProbe {
  connected: boolean;
  error: string | null;
  tables: DestinationTable[];
}

export interface DestinationProbeRequest {
  destinationType: string;
  server?: string;
  database?: string;
  authentication?: string;
  username?: string;
  password?: string;
  trustServerCertificate?: boolean;
  encrypt?: boolean;
  connectionString?: string;
  // PostgreSQL / MySQL only — see DestinationConnectionProbeRequest.RequireSsl on the backend for why this
  // defaults false rather than being hardcoded true like SQL Server's trustServerCertificate/encrypt above.
  requireSsl?: boolean;
}

export interface SftpConnectionTestRequest {
  host: string;
  port: number;
  username: string;
  password?: string;
  remoteFolder?: string;
}

// No tokenEndpoint — for "oauth2"/"clientcredentials" it's discovered server-side from baseUrl via
// GET {baseUrl}/.well-known/smart-configuration (see FhirDestinationConnectionTestService.DiscoverTokenEndpointAsync)
// rather than typed by the user.
export interface FhirConnectionTestRequest {
  baseUrl: string;
  authType: string;
  clientId?: string;
  clientSecret?: string;
  username?: string;
  password?: string;
  bearerToken?: string;
}

export interface ConnectionTestResult {
  connected: boolean;
  error: string | null;
}

/** FHIR-specific test result — adds the discovered token endpoint so the wizard can persist it into the
 *  (now-hidden) tokenEndpoint form control exactly as if the user had typed it in. */
export interface FhirConnectionTestResult extends ConnectionTestResult {
  resolvedTokenEndpoint: string | null;
}

/**
 * Tests a relational destination connection and loads its tables/columns for the pipeline builder's
 * table/column pickers. Backed by POST /api/v1/destinations/schema-preview (auth token attached by the
 * global auth interceptor).
 */
@Injectable({ providedIn: 'root' })
export class DestinationSchemaService {
  private readonly http = inject(HttpClient);

  probe(request: DestinationProbeRequest): Observable<DestinationSchemaProbe> {
    return this.http.post<DestinationSchemaProbe>(DESTINATION_ENDPOINTS.schemaPreview, request);
  }

  /** Tables/columns of an already-saved relational destination, introspected server-side using its stored
   *  secret — no credentials round-trip through the browser. Returns an empty table list (not an error) for
   *  a non-relational destination type. */
  getSchema(destinationId: string): Observable<{ destinationId: string; tables: DestinationTable[] }> {
    return this.http.get<{ destinationId: string; tables: DestinationTable[] }>(DESTINATION_ENDPOINTS.schema(destinationId));
  }

  /** Tests an ad-hoc SFTP connection for a CSV destination (storageType 'sftp'). */
  testSftp(request: SftpConnectionTestRequest): Observable<ConnectionTestResult> {
    return this.http.post<ConnectionTestResult>(DESTINATION_ENDPOINTS.sftpTest, request);
  }

  /** Tests an ad-hoc FHIR-repository connection (e.g. Aidbox) for a not-yet-saved FhirRepository destination. */
  testFhir(request: FhirConnectionTestRequest): Observable<FhirConnectionTestResult> {
    return this.http.post<FhirConnectionTestResult>(DESTINATION_ENDPOINTS.fhirTest, request);
  }
}
