import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { DESTINATION_ENDPOINTS } from '../core/api-endpoints';

export interface DestinationColumn {
  name: string;
  dataType: string;
  mappingValueType: string;
  isNullable: boolean;
  maxLength: number | null;
  /** Read from the live destination's real key constraints (SQL Server / Azure SQL only) — never guessed
   *  from the column's name. Absent/false for PostgreSQL/MySQL columns, which have no such lookup. */
  isPrimaryKey?: boolean;
  isUnique?: boolean;
  // Identity/auto-increment/computed column — the database generates its value, so it can never be a mapping
  // target or upsert key. Filtered out of the column pickers.
  isAutoGenerated?: boolean;
  isForeignKey?: boolean;
  /** Set only when isForeignKey — "{schema}.{table}.{column}" of the referenced primary key. */
  references?: string | null;
  /** Absent (e.g. every real probe() response) is treated as 'probed'. Only the mapping-canvas's own
   *  "+ Add column" flow ever stamps 'userCreated', client-side — the backend never sets this. */
  origin?: 'probed' | 'userCreated';
}

export interface DestinationTable {
  schemaName: string;
  tableName: string;
  fullName: string;
  columns: DestinationColumn[];
  /** Same convention as DestinationColumn.origin — stamped only by the "+ Add a table" flow. */
  origin?: 'probed' | 'userCreated';
}

export interface DestinationSchemaProbe {
  connected: boolean;
  error: string | null;
  tables: DestinationTable[];
}

export interface DestinationProbeRequest {
  destinationType: string;
  server?: string;
  database?: string;
  authentication?: string;
  username?: string;
  password?: string;
  trustServerCertificate?: boolean;
  encrypt?: boolean;
  connectionString?: string;
  // PostgreSQL / MySQL only — see DestinationConnectionProbeRequest.RequireSsl on the backend for why this
  // defaults false rather than being hardcoded true like SQL Server's trustServerCertificate/encrypt above.
  requireSsl?: boolean;
}

export interface SchemaMutationResult {
  success: boolean;
  error: string | null;
  column: DestinationColumn | null;
  /** Populated by createTable() — the full created table (Id + any requested columns + the FK column, if
   *  any). Also populated by addColumn() when its target table didn't already exist and had to be
   *  auto-created (Id + the one added column) — the caller otherwise has no prior record of that table. */
  table: DestinationTable | null;
}

/** One user-specified column for CreateTableRequest — name + a data type in the same shapes the
 *  add-column modal already offers (fixed keyword, sized string, or decimal(p,s)). */
export interface TableColumnDefinition {
  name: string;
  dataType: string;
}

export interface AddColumnRequest {
  connection: DestinationProbeRequest;
  tableName: string;
  columnName: string;
  dataType: string;
  isNullable?: boolean;
}

export interface CreateTableRequest {
  connection: DestinationProbeRequest;
  tableName: string;
  columns?: TableColumnDefinition[];
  /** Supplying this makes the new table a child: adds a BIGINT FK column referencing parentTable.parentColumn. */
  parentTable?: string;
  /** Defaults server-side to "Id" when parentTable is set. */
  parentColumn?: string;
  /** Defaults server-side to "{parentTableName}Id" when parentTable is set. */
  foreignKeyColumnName?: string;
}

/** Permanently drops a column via a real ALTER TABLE ... DROP COLUMN — irreversible, data included. */
export interface DropColumnRequest {
  connection: DestinationProbeRequest;
  tableName: string;
  columnName: string;
}

/** Changes an existing column's data type via a real ALTER TABLE ... ALTER COLUMN, and optionally
 *  renames it (via sp_rename) when newColumnName differs from columnName. The column's existing
 *  NULL/NOT NULL constraint is always preserved server-side. */
export interface AlterColumnRequest {
  connection: DestinationProbeRequest;
  tableName: string;
  columnName: string;
  newDataType: string;
  newColumnName?: string;
}

export interface SftpConnectionTestRequest {
  host: string;
  port: number;
  username: string;
  password?: string;
  remoteFolder?: string;
}

// No tokenEndpoint — for "oauth2"/"clientcredentials" it's discovered server-side from baseUrl via
// GET {baseUrl}/.well-known/smart-configuration (see FhirDestinationConnectionTestService.DiscoverTokenEndpointAsync)
// rather than typed by the user.
export interface FhirConnectionTestRequest {
  baseUrl: string;
  authType: string;
  clientId?: string;
  clientSecret?: string;
  username?: string;
  password?: string;
  bearerToken?: string;
}

export interface ConnectionTestResult {
  connected: boolean;
  error: string | null;
}

/** FHIR-specific test result — adds the discovered token endpoint so the wizard can persist it into the
 *  (now-hidden) tokenEndpoint form control exactly as if the user had typed it in. */
export interface FhirConnectionTestResult extends ConnectionTestResult {
  resolvedTokenEndpoint: string | null;
}

/**
 * Tests a relational destination connection and loads its tables/columns for the pipeline builder's
 * table/column pickers. Backed by POST /api/v1/destinations/schema-preview (auth token attached by the
 * global auth interceptor).
 */
@Injectable({ providedIn: 'root' })
export class DestinationSchemaService {
  private readonly http = inject(HttpClient);

  probe(request: DestinationProbeRequest): Observable<DestinationSchemaProbe> {
    return this.http.post<DestinationSchemaProbe>(DESTINATION_ENDPOINTS.schemaPreview, request);
  }

  /** Tables/columns of an already-saved relational destination, introspected server-side using its stored
   *  secret — no credentials round-trip through the browser. Returns an empty table list (not an error) for
   *  a non-relational destination type. */
  getSchema(destinationId: string): Observable<{ destinationId: string; tables: DestinationTable[] }> {
    return this.http.get<{ destinationId: string; tables: DestinationTable[] }>(DESTINATION_ENDPOINTS.schema(destinationId));
  }

  addColumn(request: AddColumnRequest): Observable<SchemaMutationResult> {
    return this.http.post<SchemaMutationResult>(DESTINATION_ENDPOINTS.addColumn, request);
  }

  createTable(request: CreateTableRequest): Observable<SchemaMutationResult> {
    return this.http.post<SchemaMutationResult>(DESTINATION_ENDPOINTS.createTable, request);
  }

  dropColumn(request: DropColumnRequest): Observable<SchemaMutationResult> {
    return this.http.post<SchemaMutationResult>(DESTINATION_ENDPOINTS.dropColumn, request);
  }

  alterColumn(request: AlterColumnRequest): Observable<SchemaMutationResult> {
    return this.http.post<SchemaMutationResult>(DESTINATION_ENDPOINTS.alterColumn, request);
  }

  /** Tests an ad-hoc SFTP connection for a CSV destination (storageType 'sftp'). */
  testSftp(request: SftpConnectionTestRequest): Observable<ConnectionTestResult> {
    return this.http.post<ConnectionTestResult>(DESTINATION_ENDPOINTS.sftpTest, request);
  }

  /** Tests an ad-hoc FHIR-repository connection (e.g. Aidbox) for a not-yet-saved FhirRepository destination. */
  testFhir(request: FhirConnectionTestRequest): Observable<FhirConnectionTestResult> {
    return this.http.post<FhirConnectionTestResult>(DESTINATION_ENDPOINTS.fhirTest, request);
  }
}
