namespace FHIRBridge.LicenseServer.Domain;

/// <summary>
/// One customer install's outbound request for a license — received either directly (<c>POST
/// /api/license-requests</c>, called by the install itself) or pasted in manually (the encoded fallback
/// blob, decoded on <c>Pages/LicenseRequests/Index</c>) when that direct call couldn't reach this server.
/// <see cref="UniqueKey"/> is generated by the requesting install, never here — it's embedded back into the
/// minted license's <c>requestKey</c> claim (see <c>Pages/Licenses/Create</c>) so that install's own
/// <c>SignedLicenseValidator</c> can refuse to apply a license minted for a different request.
/// </summary>
public sealed class LicenseRequest
{
    public Guid Id { get; set; }

    public required string ClientName { get; set; }

    public required string Email { get; set; }

    public string? CompanyName { get; set; }

    public string? Address { get; set; }

    public required string PhoneNumber { get; set; }

    /// <summary>Generated by the requesting install, immutable there across its entire license lifetime
    /// (see the main repo's <c>LicenseRequest.UniqueKey</c>) — the same value every resubmission carries,
    /// which is why this row is upserted by <see cref="UniqueKey"/> rather than inserted fresh each time.</summary>
    public required string UniqueKey { get; set; }

    public DateTime ReceivedAtUtc { get; set; }

    /// <summary>Set (again) on every resubmission — lets the list surface "just resent" separately from
    /// the original ask without needing a second table.</summary>
    public DateTime LastSubmittedUtc { get; set; }

    /// <summary>How many times this same install has submitted (1 for the original ask, 2+ for every
    /// resend/renewal since) — shown on the list so a repeat ask is visibly distinct from the first one,
    /// even though both share the one row keyed by <see cref="UniqueKey"/>.</summary>
    public int SubmissionCount { get; set; }

    /// <summary>True when this came from the manual-fallback blob (pasted in here) rather than the direct
    /// <c>POST /api/license-requests</c> call — purely informational, shown on the list.</summary>
    public bool ReceivedManually { get; set; }

    /// <summary>Set once a license has been minted against this request (see <c>Pages/Licenses/Create</c>).
    /// Null means still pending — what the dashboard notification counts. Cleared back to null on every
    /// new submission (see <c>LicenseRequestEndpoints.UpsertLicenseRequestAsync</c>) — a resend/renewal is a
    /// fresh ask that needs a fresh look, even though the previous one was already fulfilled.</summary>
    public DateTime? FulfilledAtUtc { get; set; }

    public Guid? FulfilledIssuedLicenseId { get; set; }

    public IssuedLicense? FulfilledIssuedLicense { get; set; }
}
