using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using FHIRBridge.Application.DTOs;
using FHIRBridge.Application.Services.Governance;
using FHIRBridge.Governance;

namespace FHIRBridge.Api.Operations;

/// <summary>
/// Builds the shareable Error Report a client exports from the Error Dashboard and sends to the vendor.
/// Every free-text field is re-scrubbed on the way out (<see cref="IErrorScrubber"/>), including rows captured
/// before the central scrubber existed. Contains no request/response bodies, no user identities and no PHI by design.
/// </summary>
public static class ErrorReportBuilder
{
    public const int MaxRows = 5000;

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter() },
    };

    public sealed record ReportErrorRow(
        string? ErrorReferenceId,
        DateTime OccurredOnUtc,
        string Severity,
        string? Category,
        string? Module,
        string ExceptionType,
        string Message,
        string? WhatToDo,
        string? Cause,
        string Status,
        string? CorrelationId,
        string? ExecutionId,
        string? WorkflowId,
        string? EndpointId,
        string? TraceId,
        string? StackTrace,
        string? WorkflowName = null,
        string? NodeName = null,
        string? NodeType = null,
        string? SourceName = null,
        string? DestinationName = null,
        string? ResourceType = null);

    public sealed record ErrorReport(
        string ReportType,
        DateTime GeneratedAtUtc,
        string ApplicationVersion,
        DateTime FromUtc,
        DateTime ToUtc,
        string Notice,
        ErrorDashboardDto Summary,
        IReadOnlyDictionary<string, string> AppliedFilters,
        int ExportedRows,
        bool Truncated,
        IReadOnlyList<ReportErrorRow> Errors,
        IReadOnlyDictionary<string, ErrorCorrelationDto> Correlations,
        bool CorrelationsTruncated);

    public static ErrorReport Build(
        ErrorDashboardDto summary,
        IReadOnlyList<ErrorLogDto> errors,
        bool truncated,
        bool includeStackTrace,
        string applicationVersion,
        IErrorScrubber scrubber,
        IReadOnlyDictionary<string, string>? appliedFilters = null,
        IReadOnlyDictionary<string, ErrorCorrelationDto>? correlations = null,
        bool correlationsTruncated = false)
    {
        var rows = errors.Select(e => new ReportErrorRow(
            e.ErrorReferenceId,
            e.OccurredOnUtc,
            e.Severity,
            e.Category,
            e.Module,
            e.ExceptionType,
            scrubber.ScrubText(e.Message),
            e.DiagnosisAction == "SelfFix" ? "Check your configuration" : "Contact support",
            string.IsNullOrWhiteSpace(e.DiagnosisCause) ? null : scrubber.ScrubText(e.DiagnosisCause),
            e.Status ?? "Open",
            e.CorrelationId,
            e.ExecutionId,
            e.WorkflowId,
            e.EndpointId,
            e.TraceId,
            includeStackTrace && !string.IsNullOrWhiteSpace(e.StackTrace) ? scrubber.ScrubStackTrace(e.StackTrace) : null,
            Names(scrubber, e.WorkflowName), Names(scrubber, e.NodeName), Names(scrubber, e.NodeType),
            Names(scrubber, e.SourceName), Names(scrubber, e.DestinationName), Names(scrubber, e.ResourceType)))
            .ToList();

        return new ErrorReport(
            "FHIRBridge.ErrorReport",
            DateTime.UtcNow,
            applicationVersion,
            summary.FromUtc,
            summary.ToUtc,
            "Generated by the FHIRBridge Error Dashboard. Free text has been automatically scrubbed of PHI/PII and " +
            "secrets; no request/response bodies or patient data are included. Please review before sharing.",
            summary with
            {
                TopSignatures = summary.TopSignatures
                    .Select(s => s with { SampleMessage = scrubber.ScrubText(s.SampleMessage) })
                    .ToList(),
            },
            appliedFilters ?? new Dictionary<string, string>(),
            rows.Count,
            truncated,
            rows,
            correlations ?? new Dictionary<string, ErrorCorrelationDto>(),
            correlationsTruncated);
    }

    private static string? Names(IErrorScrubber scrubber, string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : scrubber.ScrubText(value);

    public static byte[] ToJson(ErrorReport report) => JsonSerializer.SerializeToUtf8Bytes(report, JsonOptions);

    public static byte[] ToCsv(ErrorReport report)
    {
        var sb = new StringBuilder();
        sb.Append('﻿'); // BOM so Excel opens UTF-8 correctly
        sb.AppendLine(string.Join(',', new[]
        {
            "ErrorReferenceId", "OccurredOnUtc", "Severity", "Category", "Module", "ExceptionType", "Message",
            "WhatToDo", "Cause", "Status", "CorrelationId", "ExecutionId", "WorkflowId", "EndpointId", "TraceId", "StackTrace",
            "CorrelationDetails", "WorkflowName", "NodeName", "NodeType", "SourceName", "DestinationName", "ResourceType",
        }));

        // A run's timeline is written once, on the first error row that belongs to it (repeating it on every row of a
        // run would multiply the file size); later rows of the same run just point back to it.
        var written = new HashSet<string>(StringComparer.Ordinal);
        foreach (var r in report.Errors)
        {
            string? correlation = null;
            if (r.CorrelationId is not null && report.Correlations.TryGetValue(r.CorrelationId, out var timeline))
            {
                correlation = written.Add(r.CorrelationId)
                    ? CorrelationText(timeline)
                    : "(same run as an earlier row - see its CorrelationDetails)";
            }

            sb.AppendLine(string.Join(',', new[]
            {
                r.ErrorReferenceId, r.OccurredOnUtc.ToString("O"), r.Severity, r.Category, r.Module, r.ExceptionType,
                r.Message, r.WhatToDo, r.Cause, r.Status, r.CorrelationId, r.ExecutionId, r.WorkflowId, r.EndpointId,
                r.TraceId, r.StackTrace, correlation,
                r.WorkflowName, r.NodeName, r.NodeType, r.SourceName, r.DestinationName, r.ResourceType,
            }.Select(Csv)));
        }

        return Encoding.UTF8.GetBytes(sb.ToString());
    }

    public static string CorrelationText(ErrorCorrelationDto c) => ErrorCorrelationText.Format(c);

    /// <summary>RFC 4180 quoting, plus a leading apostrophe on cells a spreadsheet would execute as a formula.</summary>
    private static string Csv(string? value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;
        if (value[0] is '=' or '+' or '-' or '@' or '\t' or '\r') value = "'" + value;
        return value.IndexOfAny([',', '"', '\r', '\n']) >= 0 ? "\"" + value.Replace("\"", "\"\"") + "\"" : value;
    }
}
