using System.Data.Common;
using FHIRBridge.Application.Abstractions.Destinations;
using FHIRBridge.Application.Abstractions.Persistence;
using FHIRBridge.Application.Abstractions.Security;
using FHIRBridge.Application.DTOs;
using FHIRBridge.Domain.Enums;
using FHIRBridge.Integration.Sql;
using FHIRBridge.SharedKernel.Exceptions;
using Microsoft.Data.SqlClient;
using MySqlConnector;
using Npgsql;

namespace FHIRBridge.Infrastructure.Destinations;

/// <summary>
/// Reads the live table/column schema for a relational destination so the mapping UI can offer real column pickers,
/// and executes additive schema changes (add/create/drop/alter a column or table) for the mapping canvas's own
/// schema-authoring affordances — explicit, user-initiated actions from the "Add column"/"Create a new table…"
/// buttons, never an automatic side effect of writing mapped data (see DestinationWriterNoDdlTests, which enforces
/// that the actual record-writing path — MappedSqlServerDestinationWriter — never owns/mutates a customer's
/// schema on its own). Schema reads are provider-aware (SQL Server / Azure SQL, PostgreSQL, MySQL); schema-mutation
/// execution is SQL Server / Azure SQL only. Non-relational destinations return an empty schema (the
/// UI falls back to FHIR default tables).
/// </summary>
public sealed class SqlDestinationSchemaService : IDestinationSchemaService
{
    // __EFMigrationsHistory excluded: EF Core's own migration-bookkeeping table, not a real destination
    // table — it lives in an ordinary schema (dbo) so the schema-name filter alone doesn't catch it.
    private const string InformationSchemaSql = """
        SELECT table_schema, table_name, column_name, data_type, is_nullable, character_maximum_length,
            numeric_precision, numeric_scale
        FROM information_schema.columns
        WHERE table_schema NOT IN ('pg_catalog', 'information_schema', 'mysql', 'performance_schema', 'sys')
            AND table_name <> '__EFMigrationsHistory'
        ORDER BY table_schema, table_name, ordinal_position
        """;

    // PRIMARY KEY / UNIQUE constraint membership per column, via the ANSI-standard information_schema views shared
    // by SQL Server, PostgreSQL, and MySQL alike (see docs/backend/11-destination-schema-ownership-plan.md section 2b).
    private const string InformationSchemaConstraintsSql = """
        SELECT kcu.table_schema, kcu.table_name, kcu.column_name, tc.constraint_type
        FROM information_schema.key_column_usage kcu
        JOIN information_schema.table_constraints tc
            ON tc.constraint_name = kcu.constraint_name
            AND tc.table_schema = kcu.table_schema
            AND tc.table_name = kcu.table_name
        WHERE tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE')
            AND kcu.table_schema NOT IN ('pg_catalog', 'information_schema', 'mysql', 'performance_schema', 'sys')
        """;

    private const string SqlServerConstraintsSql = """
        SELECT kcu.TABLE_SCHEMA, kcu.TABLE_NAME, kcu.COLUMN_NAME, tc.CONSTRAINT_TYPE
        FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
        JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
            ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
            AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
            AND tc.TABLE_NAME = kcu.TABLE_NAME
        WHERE tc.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'UNIQUE')
            AND kcu.TABLE_SCHEMA NOT IN ('sys', 'INFORMATION_SCHEMA');
        """;

    // Identity/computed columns per provider — the database generates their value, so they are never a valid
    // write target or upsert key. Keyed the same "schema.table.column" way as the constraint lookup.
    private const string SqlServerAutoGeneratedSql = """
        SELECT s.name, t.name, c.name
        FROM sys.columns c
        JOIN sys.tables t ON t.object_id = c.object_id
        JOIN sys.schemas s ON s.schema_id = t.schema_id
        WHERE c.is_identity = 1 OR c.is_computed = 1;
        """;

    private const string PostgresAutoGeneratedSql = """
        SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE (is_identity = 'YES' OR is_generated = 'ALWAYS' OR column_default LIKE 'nextval(%')
            AND table_schema NOT IN ('pg_catalog', 'information_schema')
        """;

    private const string MySqlAutoGeneratedSql = """
        SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE (extra LIKE '%auto_increment%' OR extra LIKE '%GENERATED%')
            AND table_schema NOT IN ('mysql', 'performance_schema', 'sys', 'information_schema')
        """;

    private readonly IConfigurationRepository _repository;
    private readonly ISecretProvider _secretProvider;

    public SqlDestinationSchemaService(
        IConfigurationRepository repository,
        ISecretProvider secretProvider)
    {
        _repository = repository;
        _secretProvider = secretProvider;
    }

    public async Task<DestinationSchemaDto> GetSchemaAsync(
        Guid destinationId,
        CancellationToken cancellationToken)
    {
        var destination = await _repository.GetDestinationAsync(destinationId, cancellationToken)
            ?? throw new NotFoundException("DestinationConfiguration", destinationId);

        if (!IsRelational(destination.DestinationType))
        {
            return new DestinationSchemaDto(destinationId, []);
        }

        var connectionString = await _secretProvider.GetSecretAsync(destination.SecretReference, cancellationToken);
        var tables = await ReadSchemaAsync(destination.DestinationType, connectionString, cancellationToken);

        return new DestinationSchemaDto(destinationId, tables);
    }

    public async Task<DestinationSchemaProbeDto> ProbeSchemaAsync(
        DestinationConnectionProbeRequest request,
        CancellationToken cancellationToken)
    {
        if (!IsRelational(request.DestinationType))
        {
            return new DestinationSchemaProbeDto(
                false, $"Destination type '{request.DestinationType}' is not a relational database.", []);
        }

        string connectionString;
        try
        {
            connectionString = BuildConnectionString(request);
        }
        catch (Exception exception)
        {
            return new DestinationSchemaProbeDto(false, exception.Message, []);
        }

        try
        {
            var tables = await ReadSchemaAsync(request.DestinationType, connectionString, cancellationToken);
            return new DestinationSchemaProbeDto(true, null, tables);
        }
        catch (Exception exception)
        {
            // Connection/auth failures are an expected UI outcome, not a server error.
            return new DestinationSchemaProbeDto(false, exception.Message, []);
        }
    }

    public async Task<SchemaMutationResultDto> AddColumnAsync(
        AddColumnRequest request,
        CancellationToken cancellationToken)
    {
        var type = request.Connection.DestinationType;
        if (!IsRelational(type))
        {
            return new SchemaMutationResultDto(
                false, $"Destination type '{type}' does not support column creation.");
        }

        string schemaName, tableName, columnName, normalizedDataType;
        int? maxLength;
        string connectionString;
        try
        {
            (schemaName, tableName) = SplitTableName(type, request.TableName);
            columnName = SqlIdentifier.Validate(request.ColumnName);
            (normalizedDataType, maxLength) = ValidateDataType(type, request.DataType);
            connectionString = BuildConnectionString(request.Connection);
        }
        catch (Exception exception)
        {
            return new SchemaMutationResultDto(false, exception.Message);
        }

        try
        {
            await using var connection = await OpenConnectionAsync(type, connectionString, cancellationToken);

            // Never auto-create the table here — a column can only be added to a table the user
            // explicitly created (via "Create a new table…") or that already exists for real. Silently
            // creating a bare table just because its name was guessed and doesn't exist yet surprises the
            // user with schema changes they never asked for.
            if (!await TableExistsAsync(type, connection, schemaName, tableName, cancellationToken))
            {
                return new SchemaMutationResultDto(
                    false, $"Table '{DisplayTableName(type, schemaName, tableName)}' does not exist. Create it first via \"Create a new table…\".");
            }

            await using var command = connection.CreateCommand();
            // ddl-allowed: explicit user action from the mapping canvas's "Add column" affordance, not automatic
            // writer-side schema mutation. MySQL/PostgreSQL both accept (and require, for PostgreSQL) the
            // "COLUMN" keyword; SQL Server's own ADD syntax never takes one — left exactly as before for it.
            command.CommandText = type is DestinationType.MySql or DestinationType.PostgreSql
                ? $"""
                    ALTER TABLE {QuoteTable(type, schemaName, tableName)}
                    ADD COLUMN {Quote(type, columnName)} {normalizedDataType} {(request.IsNullable ? "NULL" : "NOT NULL")};
                    """
                : $"""
                    ALTER TABLE {QuoteTable(type, schemaName, tableName)}
                    ADD {Quote(type, columnName)} {normalizedDataType} {(request.IsNullable ? "NULL" : "NOT NULL")};
                    """;
            await command.ExecuteNonQueryAsync(cancellationToken);
        }
        catch (Exception exception)
        {
            // Column already exists, permission denied, etc. are expected UI outcomes — same across every
            // provider: none of them pre-check "does this column already exist" here, so a duplicate ADD
            // COLUMN fails naturally with each engine's own native error text, exactly like SQL Server always has.
            return new SchemaMutationResultDto(false, exception.Message);
        }

        var typeFamily = normalizedDataType.Split('(')[0];
        var column = new DestinationColumnSchemaDto(
            columnName, normalizedDataType, MapType(type)(typeFamily), request.IsNullable, maxLength);

        return new SchemaMutationResultDto(true, null, column);
    }

    public async Task<SchemaMutationResultDto> CreateTableAsync(
        CreateTableRequest request,
        CancellationToken cancellationToken)
    {
        var type = request.Connection.DestinationType;
        if (!IsRelational(type))
        {
            return new SchemaMutationResultDto(
                false, $"Destination type '{type}' does not support table creation.");
        }

        string schemaName, tableName, connectionString;
        var columns = new List<(string Name, string NormalizedType, int? MaxLength)>();
        (string SchemaName, string TableName, string ColumnName)? parent = null;
        string? fkColumnName = null;
        try
        {
            (schemaName, tableName) = SplitTableName(type, request.TableName);
            connectionString = BuildConnectionString(request.Connection);

            foreach (var column in request.Columns ?? [])
            {
                var name = SqlIdentifier.Validate(column.Name);
                var (normalizedType, maxLength) = ValidateDataType(type, column.DataType);
                columns.Add((name, normalizedType, maxLength));
            }

            if (!string.IsNullOrWhiteSpace(request.ParentTable))
            {
                var (parentSchema, parentTableName) = SplitTableName(type, request.ParentTable);
                var parentColumn = SqlIdentifier.Validate(
                    string.IsNullOrWhiteSpace(request.ParentColumn) ? "Id" : request.ParentColumn);
                parent = (parentSchema, parentTableName, parentColumn);
                fkColumnName = SqlIdentifier.Validate(
                    string.IsNullOrWhiteSpace(request.ForeignKeyColumnName)
                        ? $"{parentTableName}Id"
                        : request.ForeignKeyColumnName);
            }
        }
        catch (Exception exception)
        {
            return new SchemaMutationResultDto(false, exception.Message);
        }

        try
        {
            await using var connection = await OpenConnectionAsync(type, connectionString, cancellationToken);

            if (await TableExistsAsync(type, connection, schemaName, tableName, cancellationToken))
            {
                // Idempotent, not a failure: this deferred "create a table" op can legitimately reach here
                // against a table that already exists for real — e.g. the mapping canvas staged this
                // create from a local preview that never got the chance to notice a since-successful
                // earlier flush of the exact same op, or another session created it in the meantime. Never
                // re-run the DDL (would either throw a duplicate-object error or, worse, silently clobber
                // real data if it didn't), but still SUCCEED — with the table's real current shape, not
                // whatever columns were originally requested — so any queued ADD COLUMN behind this one in
                // the same flush still gets to run instead of being stranded (see AddColumnAsync's own
                // "never auto-create" comment for why a hard failure here would otherwise dead-end it).
                var liveTables = await ReadSchemaAsync(type, connectionString, cancellationToken);
                var existingTable = liveTables.FirstOrDefault(t =>
                    string.Equals(t.SchemaName, schemaName, StringComparison.OrdinalIgnoreCase)
                    && string.Equals(t.TableName, tableName, StringComparison.OrdinalIgnoreCase));
                return new SchemaMutationResultDto(true, null, Table: existingTable, AlreadyExisted: true);
            }

            if (parent is { } p && !await TableExistsAsync(type, connection, p.SchemaName, p.TableName, cancellationToken))
            {
                return new SchemaMutationResultDto(false, $"Parent table '{DisplayTableName(type, p.SchemaName, p.TableName)}' was not found.");
            }

            // MySQL has no schema layer distinct from the database (same convention MySqlMappingSchemaTransaction/
            // MappedMySqlDestinationWriter already use), and PostgreSQL's default "public" schema always
            // already exists — so only SQL Server needs (or gets) an explicit create-schema step below; a
            // non-default PostgreSQL schema that genuinely doesn't exist just fails the table-create below
            // with Postgres's own "schema does not exist" error, same never-throws/Success=false contract.
            if (type is DestinationType.SqlServer or DestinationType.AzureSql)
            {
                // ddl-allowed: explicit user action from the mapping canvas's "Create a new table…" affordance,
                // not automatic writer-side schema mutation.
                await using var createSchemaCommand = connection.CreateCommand();
                createSchemaCommand.CommandText = $"""
                    IF SCHEMA_ID(N'{schemaName}') IS NULL
                    BEGIN
                        EXEC(N'CREATE SCHEMA [{schemaName}]')
                    END
                    """;
                await createSchemaCommand.ExecuteNonQueryAsync(cancellationToken);
            }

            var columnDefinitions = new List<string> { BuildPrimaryKeyColumnDefinition(type, schemaName, tableName) };
            columnDefinitions.AddRange(columns.Select(c => $"{Quote(type, c.Name)} {c.NormalizedType} NULL"));
            if (parent is { } fk)
            {
                columnDefinitions.Add(BuildForeignKeyColumnDefinition(type, schemaName, tableName, fkColumnName!, fk));
            }
            if (type is DestinationType.MySql or DestinationType.PostgreSql)
            {
                // Both engines require PRIMARY KEY as a separate table-constraint clause rather than an
                // inline column attribute (unlike SQL Server's CONSTRAINT ... PRIMARY KEY above).
                columnDefinitions.Add($"PRIMARY KEY ({Quote(type, "Id")})");
            }

            // ddl-allowed: explicit user action from the mapping canvas's "Create a new table…" affordance, not
            // automatic writer-side schema mutation.
            await using var createTableCommand = connection.CreateCommand();
            createTableCommand.CommandText = $"""
                CREATE TABLE {QuoteTable(type, schemaName, tableName)}
                (
                    {string.Join(",\n    ", columnDefinitions)}
                );
                """;
            await createTableCommand.ExecuteNonQueryAsync(cancellationToken);
        }
        catch (Exception exception)
        {
            return new SchemaMutationResultDto(false, exception.Message);
        }

        var resultColumns = new List<DestinationColumnSchemaDto>
        {
            new("Id", "bigint", "Integer", false, null, IsPrimaryKey: true),
        };
        resultColumns.AddRange(columns.Select(c =>
            new DestinationColumnSchemaDto(c.Name, c.NormalizedType, MapType(type)(c.NormalizedType.Split('(')[0]), true, c.MaxLength)));
        if (parent is { } fkParent)
        {
            resultColumns.Add(new DestinationColumnSchemaDto(
                fkColumnName!, "bigint", "Integer", false, null,
                IsForeignKey: true, References: $"{fkParent.SchemaName}.{fkParent.TableName}.{fkParent.ColumnName}"));
        }

        var fullName = type == DestinationType.MySql ? tableName : $"{schemaName}.{tableName}";
        var table = new DestinationTableSchemaDto(schemaName, tableName, fullName, resultColumns);
        return new SchemaMutationResultDto(true, null, Table: table);
    }

    /// <summary>The always-first "Id" primary key column every CreateTableAsync table gets — auto-increment
    /// per each engine's own native mechanism: SQL Server's IDENTITY(1,1), MySQL's AUTO_INCREMENT, PostgreSQL's
    /// GENERATED ALWAYS AS IDENTITY (the SQL-standard-compliant, PostgreSQL 10+ equivalent — this app's Docker
    /// Compose stack runs postgres:16-alpine, well past that floor).</summary>
    private static string BuildPrimaryKeyColumnDefinition(DestinationType type, string schemaName, string tableName) => type switch
    {
        DestinationType.MySql => $"{Quote(type, "Id")} BIGINT AUTO_INCREMENT NOT NULL",
        DestinationType.PostgreSql => $"{Quote(type, "Id")} BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL",
        _ => $"Id BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_{schemaName}_{tableName}_Id PRIMARY KEY",
    };

    /// <summary>The child-table foreign key column CreateTableAsync adds when ParentTable is supplied — a
    /// BIGINT column plus a REFERENCES constraint against the parent's own key column.</summary>
    private static string BuildForeignKeyColumnDefinition(
        DestinationType type, string schemaName, string tableName, string fkColumnName,
        (string SchemaName, string TableName, string ColumnName) parent) => type switch
    {
        // MySQL: no parent schema prefix — same bare-table convention as everywhere else in this file for it.
        DestinationType.MySql => $"{Quote(type, fkColumnName)} BIGINT NOT NULL, " +
            $"CONSTRAINT `FK_{tableName}_{fkColumnName}` FOREIGN KEY ({Quote(type, fkColumnName)}) " +
            $"REFERENCES {Quote(type, parent.TableName)} ({Quote(type, parent.ColumnName)})",
        DestinationType.PostgreSql => $"{Quote(type, fkColumnName)} BIGINT NOT NULL, " +
            $"CONSTRAINT \"FK_{schemaName}_{tableName}_{fkColumnName}\" FOREIGN KEY ({Quote(type, fkColumnName)}) " +
            $"REFERENCES {QuoteTable(type, parent.SchemaName, parent.TableName)} ({Quote(type, parent.ColumnName)})",
        _ => $"[{fkColumnName}] BIGINT NOT NULL " +
            $"CONSTRAINT FK_{schemaName}_{tableName}_{fkColumnName} " +
            $"REFERENCES [{parent.SchemaName}].[{parent.TableName}]([{parent.ColumnName}])",
    };

    public async Task<SchemaMutationResultDto> DropColumnAsync(
        DropColumnRequest request,
        CancellationToken cancellationToken)
    {
        var type = request.Connection.DestinationType;
        if (!IsRelational(type))
        {
            return new SchemaMutationResultDto(
                false, $"Destination type '{type}' does not support dropping columns.");
        }

        string schemaName, tableName, columnName, connectionString;
        try
        {
            (schemaName, tableName) = SplitTableName(type, request.TableName);
            columnName = SqlIdentifier.Validate(request.ColumnName);
            connectionString = BuildConnectionString(request.Connection);
        }
        catch (Exception exception)
        {
            return new SchemaMutationResultDto(false, exception.Message);
        }

        try
        {
            await using var connection = await OpenConnectionAsync(type, connectionString, cancellationToken);
            await using var command = connection.CreateCommand();
            // ddl-allowed: explicit user action from the mapping canvas's column-delete affordance, not
            // automatic writer-side schema mutation. MySQL/PostgreSQL both accept "DROP COLUMN" the same as
            // SQL Server — no dialect difference here beyond identifier quoting/qualification.
            command.CommandText = $"""
                ALTER TABLE {QuoteTable(type, schemaName, tableName)}
                DROP COLUMN {Quote(type, columnName)};
                """;
            await command.ExecuteNonQueryAsync(cancellationToken);
        }
        catch (Exception exception)
        {
            // Table/column missing, column has a constraint/index depending on it, permission denied,
            // etc. are expected UI outcomes.
            return new SchemaMutationResultDto(false, exception.Message);
        }

        return new SchemaMutationResultDto(true, null);
    }

    public async Task<SchemaMutationResultDto> AlterColumnAsync(
        AlterColumnRequest request,
        CancellationToken cancellationToken)
    {
        var type = request.Connection.DestinationType;
        if (!IsRelational(type))
        {
            return new SchemaMutationResultDto(
                false, $"Destination type '{type}' does not support altering columns.");
        }

        string schemaName, tableName, columnName, normalizedDataType, connectionString;
        int? maxLength;
        string? newColumnName = null;
        try
        {
            (schemaName, tableName) = SplitTableName(type, request.TableName);
            columnName = SqlIdentifier.Validate(request.ColumnName);
            (normalizedDataType, maxLength) = ValidateDataType(type, request.NewDataType);
            if (!string.IsNullOrWhiteSpace(request.NewColumnName))
            {
                newColumnName = SqlIdentifier.Validate(request.NewColumnName);
            }
            connectionString = BuildConnectionString(request.Connection);
        }
        catch (Exception exception)
        {
            return new SchemaMutationResultDto(false, exception.Message);
        }

        var finalColumnName = columnName;
        bool isNullable;
        bool isPrimaryKey;
        string? references;
        try
        {
            await using var connection = await OpenConnectionAsync(type, connectionString, cancellationToken);
            var renaming = newColumnName is not null
                && !string.Equals(newColumnName, columnName, StringComparison.OrdinalIgnoreCase);

            if (type == DestinationType.MySql)
            {
                // MySQL's CHANGE COLUMN (unlike SQL Server's ALTER COLUMN / PostgreSQL's ALTER COLUMN TYPE)
                // requires restating the COMPLETE column definition — omitting NULL/NOT NULL doesn't
                // preserve whatever it already was the way the other two engines do, it defaults to NULL —
                // so the current nullability is read first and restated explicitly, combined with the
                // optional rename in the same single statement (CHANGE COLUMN handles both at once; MySQL
                // has no separate "RENAME COLUMN ... TYPE ..." split the way PostgreSQL does below).
                var currentlyNullable = await GetColumnNullableAsync(type, connection, schemaName, tableName, columnName, cancellationToken);
                var targetName = renaming ? newColumnName! : columnName;

                await using var changeCommand = connection.CreateCommand();
                // ddl-allowed: explicit user action from the mapping canvas's column-edit affordance, not
                // automatic writer-side schema mutation.
                changeCommand.CommandText = $"""
                    ALTER TABLE {QuoteTable(type, schemaName, tableName)}
                    CHANGE COLUMN {Quote(type, columnName)} {Quote(type, targetName)} {normalizedDataType} {(currentlyNullable ? "NULL" : "NOT NULL")};
                    """;
                await changeCommand.ExecuteNonQueryAsync(cancellationToken);
                if (renaming)
                {
                    finalColumnName = newColumnName!;
                }
            }
            else
            {
                await using var alterCommand = connection.CreateCommand();
                // ddl-allowed: explicit user action from the mapping canvas's column-edit affordance, not
                // automatic writer-side schema mutation. Unlike MySQL above, PostgreSQL's ALTER COLUMN ...
                // TYPE (like SQL Server's own ALTER COLUMN) preserves whatever NULL/NOT NULL the column
                // already had without needing to restate it.
                alterCommand.CommandText = type == DestinationType.PostgreSql
                    ? $"""
                        ALTER TABLE {QuoteTable(type, schemaName, tableName)}
                        ALTER COLUMN {Quote(type, columnName)} TYPE {normalizedDataType};
                        """
                    : $"""
                        ALTER TABLE {QuoteTable(type, schemaName, tableName)}
                        ALTER COLUMN {Quote(type, columnName)} {normalizedDataType};
                        """;
                await alterCommand.ExecuteNonQueryAsync(cancellationToken);

                if (renaming)
                {
                    await using var renameCommand = connection.CreateCommand();
                    if (type == DestinationType.PostgreSql)
                    {
                        // ddl-allowed: explicit user action from the mapping canvas's column-edit affordance
                        // (rename), not automatic writer-side schema mutation — same as the ALTER COLUMN TYPE
                        // above; SQL Server's own rename goes through sp_rename instead, in the branch below.
                        renameCommand.CommandText = $"""
                            ALTER TABLE {QuoteTable(type, schemaName, tableName)}
                            RENAME COLUMN {Quote(type, columnName)} TO {Quote(type, newColumnName!)};
                            """;
                    }
                    else
                    {
                        renameCommand.CommandText = "EXEC sp_rename @objname, @newname, N'COLUMN';";
                        AddParameter(renameCommand, "@objname", $"{schemaName}.{tableName}.{columnName}");
                        AddParameter(renameCommand, "@newname", newColumnName!);
                    }
                    await renameCommand.ExecuteNonQueryAsync(cancellationToken);
                    finalColumnName = newColumnName!;
                }
            }

            isNullable = await GetColumnNullableAsync(type, connection, schemaName, tableName, finalColumnName, cancellationToken);
            (isPrimaryKey, references) = await GetColumnKeyInfoAsync(type, connection, schemaName, tableName, finalColumnName, cancellationToken);
        }
        catch (Exception exception)
        {
            // Incompatible type conversion, new name collides with an existing column, table/column
            // missing, permission denied, etc. are expected UI outcomes.
            return new SchemaMutationResultDto(false, exception.Message);
        }

        var typeFamily = normalizedDataType.Split('(')[0];
        var column = new DestinationColumnSchemaDto(
            finalColumnName, normalizedDataType, MapType(type)(typeFamily), isNullable, maxLength,
            IsPrimaryKey: isPrimaryKey, IsForeignKey: references is not null, References: references);
        return new SchemaMutationResultDto(true, null, column);
    }

    private static void AddParameter(DbCommand command, string name, object value)
    {
        var parameter = command.CreateParameter();
        parameter.ParameterName = name;
        parameter.Value = value;
        command.Parameters.Add(parameter);
    }

    /// <summary>Definitive post-ALTER nullability, read back from the catalog rather than assumed — SQL
    /// Server's ALTER COLUMN / PostgreSQL's ALTER COLUMN ... TYPE both deliberately omit NULL/NOT NULL to
    /// preserve whatever it already was, so this is the only way to know what that ended up being. For
    /// MySQL it's also read BEFORE the alter (see AlterColumnAsync) — its CHANGE COLUMN has no such
    /// preserving behavior and must restate nullability explicitly.
    ///
    /// ANSI-standard INFORMATION_SCHEMA.COLUMNS, portable across all three providers — SQL Server and
    /// PostgreSQL both have a real, non-empty schemaName to filter on (SplitTableName's "dbo"/"public"
    /// default), but MySQL's own TABLE_SCHEMA column is the CONNECTED DATABASE's name, not a real,
    /// separately-addressable schema — SplitTableName deliberately never resolves one for MySQL (see its own
    /// doc comment), so DATABASE() is used directly in the query instead of a parameterized, necessarily-empty
    /// schemaName.</summary>
    private static async Task<bool> GetColumnNullableAsync(
        DestinationType type, DbConnection connection, string schemaName, string tableName, string columnName, CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = type == DestinationType.MySql
            ? "SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table AND COLUMN_NAME = @column;"
            : "SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @schema AND TABLE_NAME = @table AND COLUMN_NAME = @column;";
        if (type != DestinationType.MySql)
        {
            AddParameter(command, "@schema", schemaName);
        }
        AddParameter(command, "@table", tableName);
        AddParameter(command, "@column", columnName);
        var result = await command.ExecuteScalarAsync(cancellationToken);
        return result is string s && string.Equals(s, "YES", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>Provider-aware "does this table exist right now" — SQL Server keeps its existing OBJECT_ID
    /// lookup unchanged; MySQL/PostgreSQL use the ANSI-standard INFORMATION_SCHEMA.TABLES (MySQL scoped via
    /// DATABASE() rather than a parameterized schema — see GetColumnNullableAsync's doc comment for why).</summary>
    private static async Task<bool> TableExistsAsync(
        DestinationType type, DbConnection connection, string schemaName, string tableName, CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        if (type is DestinationType.MySql or DestinationType.PostgreSql)
        {
            command.CommandText = type == DestinationType.MySql
                ? "SELECT COUNT(1) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = @table;"
                : "SELECT COUNT(1) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = @schema AND TABLE_NAME = @table;";
            if (type == DestinationType.PostgreSql)
            {
                AddParameter(command, "@schema", schemaName);
            }
            AddParameter(command, "@table", tableName);
            var count = Convert.ToInt64(await command.ExecuteScalarAsync(cancellationToken));
            return count > 0;
        }

        command.CommandText = $"SELECT OBJECT_ID(N'[{schemaName}].[{tableName}]', N'U');";
        var result = await command.ExecuteScalarAsync(cancellationToken);
        return result is not null and not DBNull;
    }

    /// <summary>Splits a (possibly schema-qualified) table name per the target engine's own convention.
    /// SQL Server/PostgreSQL: schema.table, defaulting to each engine's real default schema ("dbo"/"public")
    /// when unqualified — unchanged for SQL Server, same shape for PostgreSQL. MySQL: ALWAYS bare — MySQL has
    /// no schema layer distinct from the database (same convention MySqlMappingSchemaTransaction/
    /// MappedMySqlDestinationWriter already use elsewhere), and a "prefix." on a MySQL table name here is
    /// really the CONNECTED DATABASE's own name (from the live schema probe's fullName, e.g.
    /// "my_database.Patient" — see ReadColumnsAsync), never a real, separately-selectable MySQL schema — so
    /// it's discarded (just the last dot-segment is kept) rather than treated as a schema qualifier.</summary>
    private static (string SchemaName, string TableName) SplitTableName(DestinationType type, string tableName)
    {
        if (type == DestinationType.MySql)
        {
            var lastDot = tableName.LastIndexOf('.');
            var bare = lastDot >= 0 ? tableName[(lastDot + 1)..] : tableName;
            return ("", SqlIdentifier.Validate(bare));
        }

        var defaultSchema = type == DestinationType.PostgreSql ? "public" : "dbo";
        var parts = tableName.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        return parts switch
        {
            [var table] => (defaultSchema, SqlIdentifier.Validate(table)),
            [var schema, var table] => (SqlIdentifier.Validate(schema), SqlIdentifier.Validate(table)),
            _ => throw new InvalidOperationException($"'{tableName}' must be either TableName or SchemaName.TableName.")
        };
    }

    private static (string NormalizedType, int? MaxLength) ValidateDataType(DestinationType type, string dataType) => type switch
    {
        DestinationType.MySql => MySqlDdlTypeValidator.Validate(dataType),
        DestinationType.PostgreSql => PostgreSqlDdlTypeValidator.Validate(dataType),
        _ => SqlServerDdlTypeValidator.Validate(dataType),
    };

    /// <summary>Wraps a single identifier in the target engine's own quoting syntax — SQL Server "[x]",
    /// MySQL "`x`", PostgreSQL "\"x\"". The one place every mutation method's generated DDL gets its
    /// identifier quoting from, so the three conventions can never drift apart or get mixed up.</summary>
    private static string Quote(DestinationType type, string identifier) => type switch
    {
        DestinationType.MySql => $"`{identifier}`",
        DestinationType.PostgreSql => $"\"{identifier}\"",
        _ => $"[{identifier}]",
    };

    /// <summary>A table reference ready to embed in DDL/DML — schema-qualified for SQL Server/PostgreSQL
    /// ("[dbo].[Patient]" / "\"public\".\"Patient\""), bare for MySQL ("`Patient`" — see SplitTableName's own
    /// doc comment for why MySQL never carries a real schema to qualify with).</summary>
    private static string QuoteTable(DestinationType type, string schemaName, string tableName) => type switch
    {
        DestinationType.MySql => Quote(type, tableName),
        _ => $"{Quote(type, schemaName)}.{Quote(type, tableName)}",
    };

    /// <summary>Human-readable "schema.table" (or just "table" for MySQL) for an error message — never used
    /// in actual DDL (see QuoteTable for that), just what the user sees when a table can't be found.</summary>
    private static string DisplayTableName(DestinationType type, string schemaName, string tableName) =>
        type == DestinationType.MySql ? tableName : $"{schemaName}.{tableName}";

    private async Task<List<DestinationTableSchemaDto>> ReadSchemaAsync(
        DestinationType type,
        string connectionString,
        CancellationToken cancellationToken)
    {
        await using var connection = await OpenConnectionAsync(type, connectionString, cancellationToken);
        var isSqlServer = type is DestinationType.SqlServer or DestinationType.AzureSql;

        var constraints = await ReadConstraintsAsync(connection, isSqlServer, cancellationToken);
        var autoGenerated = await ReadAutoGeneratedAsync(connection, type, cancellationToken);
        // FK reference targets are only readable from SQL Server's own sys.* catalog views —
        // PostgreSQL/MySQL columns keep References=null (see DestinationColumnSchemaDto's own doc comment).
        var keyMetadata = isSqlServer
            ? await ReadSqlServerKeyMetadataAsync(connection, cancellationToken)
            : new Dictionary<string, (bool IsPrimaryKey, string? References)>();

        await using var command = connection.CreateCommand();
        command.CommandText = isSqlServer ? SqlServerColumnsSql : InformationSchemaSql;

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        return await ReadColumnsAsync(reader, MapType(type), constraints, autoGenerated, keyMetadata, cancellationToken);
    }

    /// <summary>
    /// One row per column that is a primary key and/or a foreign key, across every table in the database —
    /// read once per probe/schema-load and merged into ReadColumnsAsync's per-column output by "schema.table.column"
    /// key, rather than guessing PK/FK from a column's name (e.g. "Id", "{Table}Id"). Composite keys spanning
    /// several columns still report each participating column's own IsPrimaryKey/References independently.
    /// </summary>
    private static async Task<Dictionary<string, (bool IsPrimaryKey, string? References)>> ReadSqlServerKeyMetadataAsync(
        DbConnection connection,
        CancellationToken cancellationToken)
    {
        var metadata = new Dictionary<string, (bool IsPrimaryKey, string? References)>(StringComparer.OrdinalIgnoreCase);

        await using var command = connection.CreateCommand();
        command.CommandText = SqlServerBulkKeyMetadataSql;
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            var key = $"{reader.GetString(0)}.{reader.GetString(1)}.{reader.GetString(2)}";
            var isPrimaryKey = reader.GetInt32(3) == 1;
            string? references = reader.IsDBNull(4)
                ? null
                : $"{reader.GetString(4)}.{reader.GetString(5)}.{reader.GetString(6)}";

            metadata[key] = metadata.TryGetValue(key, out var existing)
                ? (existing.IsPrimaryKey || isPrimaryKey, existing.References ?? references)
                : (isPrimaryKey, references);
        }

        return metadata;
    }

    /// <summary>Same PK/FK lookup as <see cref="ReadSqlServerKeyMetadataAsync"/>, scoped to one already-known
    /// column — used right after AlterColumnAsync's rename/retype, where re-running the bulk, whole-database
    /// query would be wasteful for a single column whose key status could only be reported stale otherwise.</summary>
    private static async Task<(bool IsPrimaryKey, string? References)> GetColumnKeyInfoAsync(
        DestinationType type,
        DbConnection connection,
        string schemaName,
        string tableName,
        string columnName,
        CancellationToken cancellationToken)
    {
        // FK reference targets are only readable from SQL Server's own sys.* catalog views — PostgreSQL/
        // MySQL columns keep References=null here, same established limitation ReadSchemaAsync already has
        // for a live-probed column (see DestinationColumnSchemaDto's own doc comment) — only PK status is
        // determined for them, via the same ANSI-standard information_schema join InformationSchemaConstraintsSql
        // already uses for the read path, scoped to one column instead of the whole database.
        if (type is DestinationType.MySql or DestinationType.PostgreSql)
        {
            await using var ansiCommand = connection.CreateCommand();
            ansiCommand.CommandText = type == DestinationType.MySql
                ? """
                    SELECT tc.constraint_type
                    FROM information_schema.key_column_usage kcu
                    JOIN information_schema.table_constraints tc
                        ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
                    WHERE kcu.table_schema = DATABASE() AND kcu.table_name = @table AND kcu.column_name = @column;
                    """
                : """
                    SELECT tc.constraint_type
                    FROM information_schema.key_column_usage kcu
                    JOIN information_schema.table_constraints tc
                        ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
                    WHERE kcu.table_schema = @schema AND kcu.table_name = @table AND kcu.column_name = @column;
                    """;
            if (type == DestinationType.PostgreSql)
            {
                AddParameter(ansiCommand, "@schema", schemaName);
            }
            AddParameter(ansiCommand, "@table", tableName);
            AddParameter(ansiCommand, "@column", columnName);

            var isPk = false;
            await using var ansiReader = await ansiCommand.ExecuteReaderAsync(cancellationToken);
            while (await ansiReader.ReadAsync(cancellationToken))
            {
                if (string.Equals(ansiReader.GetString(0), "PRIMARY KEY", StringComparison.OrdinalIgnoreCase))
                {
                    isPk = true;
                }
            }
            return (isPk, null);
        }

        await using var command = connection.CreateCommand();
        command.CommandText = SqlServerSingleColumnKeyMetadataSql;
        AddParameter(command, "@schema", schemaName);
        AddParameter(command, "@table", tableName);
        AddParameter(command, "@column", columnName);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        if (!await reader.ReadAsync(cancellationToken))
        {
            return (false, null);
        }

        var isPrimaryKey = reader.GetInt32(0) == 1;
        string? references = reader.IsDBNull(1) ? null : $"{reader.GetString(1)}.{reader.GetString(2)}.{reader.GetString(3)}";
        return (isPrimaryKey, references);
    }

    /// <summary>
    /// Column -> (IsPrimaryKey, IsUnique) membership, keyed by "schema.table.column" (case-insensitive). A column can
    /// appear under more than one constraint (e.g. its own unique index plus being part of the primary key), so flags
    /// are OR-merged rather than overwritten.
    /// </summary>
    private static async Task<Dictionary<string, (bool IsPrimaryKey, bool IsUnique)>> ReadConstraintsAsync(
        DbConnection connection,
        bool isSqlServer,
        CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = isSqlServer ? SqlServerConstraintsSql : InformationSchemaConstraintsSql;

        var constraints = new Dictionary<string, (bool IsPrimaryKey, bool IsUnique)>(StringComparer.OrdinalIgnoreCase);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            var key = ConstraintKey(reader.GetString(0), reader.GetString(1), reader.GetString(2));
            var isPrimaryKey = string.Equals(reader.GetString(3), "PRIMARY KEY", StringComparison.OrdinalIgnoreCase);

            var existing = constraints.TryGetValue(key, out var current) ? current : (false, false);
            constraints[key] = (existing.Item1 || isPrimaryKey, true);
        }

        return constraints;
    }

    /// <summary>Set of "schema.table.column" keys for columns the database auto-generates (identity/auto-increment
    /// /computed) and therefore can never be written to. Empty for providers without a supported query.</summary>
    private static async Task<HashSet<string>> ReadAutoGeneratedAsync(
        DbConnection connection,
        DestinationType type,
        CancellationToken cancellationToken)
    {
        var sql = type switch
        {
            DestinationType.SqlServer or DestinationType.AzureSql => SqlServerAutoGeneratedSql,
            DestinationType.PostgreSql => PostgresAutoGeneratedSql,
            DestinationType.MySql => MySqlAutoGeneratedSql,
            _ => null,
        };

        var autoGenerated = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (sql is null)
        {
            return autoGenerated;
        }

        await using var command = connection.CreateCommand();
        command.CommandText = sql;

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            autoGenerated.Add(ConstraintKey(reader.GetString(0), reader.GetString(1), reader.GetString(2)));
        }

        return autoGenerated;
    }

    private static string ConstraintKey(string schema, string table, string column) => $"{schema}.{table}.{column}";

    private static string BuildConnectionString(DestinationConnectionProbeRequest request)
    {
        if (!string.IsNullOrWhiteSpace(request.ConnectionString))
        {
            return request.ConnectionString!;
        }

        return request.DestinationType switch
        {
            DestinationType.SqlServer or DestinationType.AzureSql => BuildSqlServerConnectionString(request),
            DestinationType.MySql => BuildMySqlConnectionString(request),
            DestinationType.PostgreSql => BuildPostgreSqlConnectionString(request),
            _ => throw new InvalidOperationException(
                $"Provide a ConnectionString to probe destination type '{request.DestinationType}'."),
        };
    }

    private static string BuildPostgreSqlConnectionString(DestinationConnectionProbeRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Server) || string.IsNullOrWhiteSpace(request.Database))
        {
            throw new InvalidOperationException("Server and Database are required to test a PostgreSQL connection.");
        }

        var builder = new NpgsqlConnectionStringBuilder
        {
            Host = request.Server,
            Database = request.Database,
            Username = request.Username ?? string.Empty,
            Password = request.Password ?? string.Empty,
            Timeout = 10,
            // Require (unlike VerifyCA/VerifyFull) does not validate the server certificate — the Npgsql 6+
            // equivalent of the old TrustServerCertificate=true behavior, so no extra flag is needed here.
            SslMode = request.RequireSsl ? SslMode.Require : SslMode.Prefer,
        };

        return builder.ConnectionString;
    }

    private static string BuildMySqlConnectionString(DestinationConnectionProbeRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Server) || string.IsNullOrWhiteSpace(request.Database))
        {
            throw new InvalidOperationException("Server and Database are required to test a MySQL connection.");
        }

        var builder = new MySqlConnectionStringBuilder
        {
            Server = request.Server,
            Database = request.Database,
            UserID = request.Username ?? string.Empty,
            Password = request.Password ?? string.Empty,
            ConnectionTimeout = 10,
            // MySqlConnector's "Required" mode encrypts without validating the server certificate — the same
            // "SSL on, don't verify" behavior Npgsql gets from SslMode.Require + TrustServerCertificate above.
            SslMode = request.RequireSsl ? MySqlSslMode.Required : MySqlSslMode.Preferred,
        };

        return builder.ConnectionString;
    }

    private static string BuildSqlServerConnectionString(DestinationConnectionProbeRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Server) || string.IsNullOrWhiteSpace(request.Database))
        {
            throw new InvalidOperationException("Server and Database are required to test a SQL Server connection.");
        }

        var builder = new SqlConnectionStringBuilder
        {
            DataSource = request.Server,
            InitialCatalog = request.Database,
            TrustServerCertificate = request.TrustServerCertificate,
            Encrypt = request.Encrypt,
            ConnectTimeout = 10,
        };

        switch ((request.Authentication ?? "sql-auth").Trim().ToLowerInvariant())
        {
            case "managed-identity":
                builder.Authentication = SqlAuthenticationMethod.ActiveDirectoryManagedIdentity;
                break;
            case "azure-ad":
                builder.Authentication = SqlAuthenticationMethod.ActiveDirectoryDefault;
                break;
            default: // sql-auth
                builder.UserID = request.Username ?? string.Empty;
                builder.Password = request.Password ?? string.Empty;
                break;
        }

        return builder.ConnectionString;
    }

    private static bool IsRelational(DestinationType type)
        => type is DestinationType.SqlServer or DestinationType.AzureSql or DestinationType.PostgreSql or DestinationType.MySql;

    private static async Task<DbConnection> OpenConnectionAsync(
        DestinationType type,
        string connectionString,
        CancellationToken cancellationToken)
    {
        switch (type)
        {
            case DestinationType.SqlServer:
            case DestinationType.AzureSql:
                return await SqlServerConnectionFactory.OpenConnectionAsync(connectionString, cancellationToken);
            case DestinationType.PostgreSql:
                var npgsql = new NpgsqlConnection(connectionString);
                await npgsql.OpenAsync(cancellationToken);
                return npgsql;
            case DestinationType.MySql:
                var mysql = new MySqlConnection(connectionString);
                await mysql.OpenAsync(cancellationToken);
                return mysql;
            default:
                throw new InvalidOperationException($"Destination type '{type}' is not relational.");
        }
    }

    // __EFMigrationsHistory excluded: EF Core's own migration-bookkeeping table, not a real destination
    // table — it lives in an ordinary schema (dbo) so the schema-name filter alone doesn't catch it.
    private const string SqlServerColumnsSql = """
        SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH,
            NUMERIC_PRECISION, NUMERIC_SCALE
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA NOT IN ('sys', 'INFORMATION_SCHEMA')
            AND TABLE_NAME <> '__EFMigrationsHistory'
        ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;
        """;

    // Only columns that ARE a primary key and/or a foreign key are returned — every other column is
    // implicitly neither, so the result set stays small regardless of database size. ReferencedSchema/
    // ReferencedTable/ReferencedColumn are NULL for a plain (non-FK) primary key column.
    private const string SqlServerBulkKeyMetadataSql = """
        SELECT s.name, t.name, c.name,
               CASE WHEN pk.column_id IS NOT NULL THEN 1 ELSE 0 END,
               rs.name, rt.name, rc.name
        FROM sys.columns c
        JOIN sys.tables t ON t.object_id = c.object_id
        JOIN sys.schemas s ON s.schema_id = t.schema_id
        LEFT JOIN (
            SELECT ic.object_id, ic.column_id
            FROM sys.index_columns ic
            JOIN sys.indexes i ON i.object_id = ic.object_id AND i.index_id = ic.index_id
            WHERE i.is_primary_key = 1
        ) pk ON pk.object_id = c.object_id AND pk.column_id = c.column_id
        LEFT JOIN sys.foreign_key_columns fkc ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
        LEFT JOIN sys.tables rt ON rt.object_id = fkc.referenced_object_id
        LEFT JOIN sys.schemas rs ON rs.schema_id = rt.schema_id
        LEFT JOIN sys.columns rc ON rc.object_id = fkc.referenced_object_id AND rc.column_id = fkc.referenced_column_id
        WHERE s.name NOT IN ('sys', 'INFORMATION_SCHEMA') AND (pk.column_id IS NOT NULL OR fkc.parent_column_id IS NOT NULL);
        """;

    // Same PK/FK shape as SqlServerBulkKeyMetadataSql, scoped to one column via @schema/@table/@column.
    private const string SqlServerSingleColumnKeyMetadataSql = """
        SELECT CASE WHEN pk.column_id IS NOT NULL THEN 1 ELSE 0 END,
               rs.name, rt.name, rc.name
        FROM sys.columns c
        JOIN sys.tables t ON t.object_id = c.object_id AND t.name = @table
        JOIN sys.schemas s ON s.schema_id = t.schema_id AND s.name = @schema
        LEFT JOIN (
            SELECT ic.object_id, ic.column_id
            FROM sys.index_columns ic
            JOIN sys.indexes i ON i.object_id = ic.object_id AND i.index_id = ic.index_id
            WHERE i.is_primary_key = 1
        ) pk ON pk.object_id = c.object_id AND pk.column_id = c.column_id
        LEFT JOIN sys.foreign_key_columns fkc ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
        LEFT JOIN sys.tables rt ON rt.object_id = fkc.referenced_object_id
        LEFT JOIN sys.schemas rs ON rs.schema_id = rt.schema_id
        LEFT JOIN sys.columns rc ON rc.object_id = fkc.referenced_object_id AND rc.column_id = fkc.referenced_column_id
        WHERE c.name = @column;
        """;

    private static async Task<List<DestinationTableSchemaDto>> ReadColumnsAsync(
        DbDataReader reader,
        Func<string, string> mapType,
        IReadOnlyDictionary<string, (bool IsPrimaryKey, bool IsUnique)> constraints,
        IReadOnlySet<string> autoGenerated,
        IReadOnlyDictionary<string, (bool IsPrimaryKey, string? References)> keyMetadata,
        CancellationToken cancellationToken)
    {
        var tables = new Dictionary<string, List<DestinationColumnSchemaDto>>(StringComparer.OrdinalIgnoreCase);
        var tableNames = new Dictionary<string, (string SchemaName, string TableName)>(StringComparer.OrdinalIgnoreCase);

        while (await reader.ReadAsync(cancellationToken))
        {
            var schemaName = reader.GetString(0);
            var tableName = reader.GetString(1);
            var columnName = reader.GetString(2);
            var fullName = $"{schemaName}.{tableName}";
            var dataType = reader.GetString(3);

            // character_maximum_length can exceed int range (e.g. MySQL LONGTEXT) — clamp oversized values to null.
            int? maxLength = null;
            if (!reader.IsDBNull(5))
            {
                var raw = Convert.ToInt64(reader.GetValue(5));
                maxLength = raw is > 0 and <= int.MaxValue ? (int)raw : null;
            }

            int? numericPrecision = reader.IsDBNull(6) ? null : Convert.ToInt32(reader.GetValue(6));
            int? numericScale = reader.IsDBNull(7) ? null : Convert.ToInt32(reader.GetValue(7));

            if (!tables.TryGetValue(fullName, out var columns))
            {
                columns = [];
                tables[fullName] = columns;
                tableNames[fullName] = (schemaName, tableName);
            }

            var columnKey = ConstraintKey(schemaName, tableName, columnName);
            var (isPrimaryKey, isUnique) = constraints.TryGetValue(columnKey, out var flags)
                ? flags
                : (false, false);
            var (isPrimaryKeyFromKeyMetadata, references) = keyMetadata.TryGetValue(columnKey, out var key)
                ? key
                : (false, null);

            columns.Add(new DestinationColumnSchemaDto(
                columnName,
                dataType,
                mapType(dataType),
                string.Equals(reader.GetString(4), "YES", StringComparison.OrdinalIgnoreCase),
                maxLength,
                isPrimaryKey || isPrimaryKeyFromKeyMetadata,
                isUnique,
                autoGenerated.Contains(columnKey),
                numericPrecision,
                numericScale,
                IsForeignKey: references is not null,
                References: references));
        }

        return tables
            .Select(pair =>
            {
                var (schemaName, tableName) = tableNames[pair.Key];
                return new DestinationTableSchemaDto(schemaName, tableName, pair.Key, pair.Value);
            })
            .ToList();
    }

    private static Func<string, string> MapType(DestinationType type)
        => type switch
        {
            DestinationType.PostgreSql => MapPostgresType,
            DestinationType.MySql => MapMySqlType,
            _ => MapSqlServerType
        };

    private static string MapSqlServerType(string dataType) => dataType.Trim().ToLowerInvariant() switch
    {
        "bit" => "Boolean",
        "tinyint" or "smallint" or "int" or "bigint" => "Integer",
        "decimal" or "numeric" or "money" or "smallmoney" or "float" or "real" => "Decimal",
        "date" => "Date",
        "datetime" or "datetime2" or "datetimeoffset" or "smalldatetime" => "DateTime",
        _ => "String"
    };

    private static string MapPostgresType(string dataType) => dataType.Trim().ToLowerInvariant() switch
    {
        "boolean" => "Boolean",
        "smallint" or "integer" or "bigint" => "Integer",
        "numeric" or "decimal" or "real" or "double precision" or "money" => "Decimal",
        "date" => "Date",
        // "timestamp without time zone"/"timestamp with time zone" are what a LIVE probe reports for an
        // already-existing column; plain "timestamp" is what PostgreSqlDdlTypeValidator normalizes a
        // newly-created column's type to (see CreateTableAsync/AddColumnAsync) — both mean the same thing.
        "timestamp without time zone" or "timestamp with time zone" or "timestamp" => "DateTime",
        _ => "String"
    };

    private static string MapMySqlType(string dataType) => dataType.Trim().ToLowerInvariant() switch
    {
        // MySQL has no native boolean storage type — BOOLEAN/BOOL are aliases for TINYINT(1), and the
        // frontend's own SQL-Server-flavored "bit" default (see MySqlDdlTypeValidator) is kept as MySQL's
        // real BIT type rather than translated, so all three read back as the same logical Boolean.
        "tinyint" or "boolean" or "bool" or "bit" => "Boolean",
        "smallint" or "mediumint" or "int" or "integer" or "bigint" => "Integer",
        "decimal" or "numeric" or "float" or "double" => "Decimal",
        "date" => "Date",
        "datetime" or "timestamp" => "DateTime",
        _ => "String"
    };
}
