using System.Data.Common;
using FHIRBridge.Application.Abstractions.Destinations;
using FHIRBridge.Application.Abstractions.Persistence;
using FHIRBridge.Application.Abstractions.Security;
using FHIRBridge.Application.DTOs;
using FHIRBridge.Domain.Enums;
using FHIRBridge.Integration.Sql;
using FHIRBridge.SharedKernel.Exceptions;
using Microsoft.Data.SqlClient;
using MySqlConnector;
using Npgsql;

namespace FHIRBridge.Infrastructure.Destinations;

/// <summary>
/// Reads the live table/column schema for a relational destination so the mapping UI can offer real column pickers.
/// Provider-aware: SQL Server / Azure SQL, PostgreSQL, and MySQL are introspected via <c>information_schema.columns</c>.
/// Non-relational destinations return an empty schema (the UI falls back to FHIR default tables).
/// </summary>
public sealed class SqlDestinationSchemaService : IDestinationSchemaService
{
    private const string InformationSchemaSql = """
        SELECT table_schema, table_name, column_name, data_type, is_nullable, character_maximum_length
        FROM information_schema.columns
        WHERE table_schema NOT IN ('pg_catalog', 'information_schema', 'mysql', 'performance_schema', 'sys')
        ORDER BY table_schema, table_name, ordinal_position
        """;

    // PRIMARY KEY / UNIQUE constraint membership per column, via the ANSI-standard information_schema views shared
    // by SQL Server, PostgreSQL, and MySQL alike (see docs/backend/11-destination-schema-ownership-plan.md section 2b).
    private const string InformationSchemaConstraintsSql = """
        SELECT kcu.table_schema, kcu.table_name, kcu.column_name, tc.constraint_type
        FROM information_schema.key_column_usage kcu
        JOIN information_schema.table_constraints tc
            ON tc.constraint_name = kcu.constraint_name
            AND tc.table_schema = kcu.table_schema
            AND tc.table_name = kcu.table_name
        WHERE tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE')
            AND kcu.table_schema NOT IN ('pg_catalog', 'information_schema', 'mysql', 'performance_schema', 'sys')
        """;

    private const string SqlServerConstraintsSql = """
        SELECT kcu.TABLE_SCHEMA, kcu.TABLE_NAME, kcu.COLUMN_NAME, tc.CONSTRAINT_TYPE
        FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
        JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
            ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
            AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
            AND tc.TABLE_NAME = kcu.TABLE_NAME
        WHERE tc.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'UNIQUE')
            AND kcu.TABLE_SCHEMA NOT IN ('sys', 'INFORMATION_SCHEMA');
        """;

    // Identity/computed columns per provider — the database generates their value, so they are never a valid
    // write target or upsert key. Keyed the same "schema.table.column" way as the constraint lookup.
    private const string SqlServerAutoGeneratedSql = """
        SELECT s.name, t.name, c.name
        FROM sys.columns c
        JOIN sys.tables t ON t.object_id = c.object_id
        JOIN sys.schemas s ON s.schema_id = t.schema_id
        WHERE c.is_identity = 1 OR c.is_computed = 1;
        """;

    private const string PostgresAutoGeneratedSql = """
        SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE (is_identity = 'YES' OR is_generated = 'ALWAYS' OR column_default LIKE 'nextval(%')
            AND table_schema NOT IN ('pg_catalog', 'information_schema')
        """;

    private const string MySqlAutoGeneratedSql = """
        SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE (extra LIKE '%auto_increment%' OR extra LIKE '%GENERATED%')
            AND table_schema NOT IN ('mysql', 'performance_schema', 'sys', 'information_schema')
        """;

    private readonly IConfigurationRepository _repository;
    private readonly ISecretProvider _secretProvider;

    public SqlDestinationSchemaService(
        IConfigurationRepository repository,
        ISecretProvider secretProvider)
    {
        _repository = repository;
        _secretProvider = secretProvider;
    }

    public async Task<DestinationSchemaDto> GetSchemaAsync(
        Guid destinationId,
        CancellationToken cancellationToken)
    {
        var destination = await _repository.GetDestinationAsync(destinationId, cancellationToken)
            ?? throw new NotFoundException("DestinationConfiguration", destinationId);

        if (!IsRelational(destination.DestinationType))
        {
            return new DestinationSchemaDto(destinationId, []);
        }

        var connectionString = await _secretProvider.GetSecretAsync(destination.SecretReference, cancellationToken);
        var tables = await ReadSchemaAsync(destination.DestinationType, connectionString, cancellationToken);

        return new DestinationSchemaDto(destinationId, tables);
    }

    public async Task<DestinationSchemaProbeDto> ProbeSchemaAsync(
        DestinationConnectionProbeRequest request,
        CancellationToken cancellationToken)
    {
        if (!IsRelational(request.DestinationType))
        {
            return new DestinationSchemaProbeDto(
                false, $"Destination type '{request.DestinationType}' is not a relational database.", []);
        }

        string connectionString;
        try
        {
            connectionString = BuildConnectionString(request);
        }
        catch (Exception exception)
        {
            return new DestinationSchemaProbeDto(false, exception.Message, []);
        }

        try
        {
            var tables = await ReadSchemaAsync(request.DestinationType, connectionString, cancellationToken);
            return new DestinationSchemaProbeDto(true, null, tables);
        }
        catch (Exception exception)
        {
            // Connection/auth failures are an expected UI outcome, not a server error.
            return new DestinationSchemaProbeDto(false, exception.Message, []);
        }
    }

    private async Task<List<DestinationTableSchemaDto>> ReadSchemaAsync(
        DestinationType type,
        string connectionString,
        CancellationToken cancellationToken)
    {
        await using var connection = await OpenConnectionAsync(type, connectionString, cancellationToken);
        var isSqlServer = type is DestinationType.SqlServer or DestinationType.AzureSql;

        var constraints = await ReadConstraintsAsync(connection, isSqlServer, cancellationToken);
        var autoGenerated = await ReadAutoGeneratedAsync(connection, type, cancellationToken);

        await using var command = connection.CreateCommand();
        command.CommandText = isSqlServer ? SqlServerColumnsSql : InformationSchemaSql;

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        return await ReadColumnsAsync(reader, MapType(type), constraints, autoGenerated, cancellationToken);
    }

    /// <summary>
    /// Column -> (IsPrimaryKey, IsUnique) membership, keyed by "schema.table.column" (case-insensitive). A column can
    /// appear under more than one constraint (e.g. its own unique index plus being part of the primary key), so flags
    /// are OR-merged rather than overwritten.
    /// </summary>
    private static async Task<Dictionary<string, (bool IsPrimaryKey, bool IsUnique)>> ReadConstraintsAsync(
        DbConnection connection,
        bool isSqlServer,
        CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = isSqlServer ? SqlServerConstraintsSql : InformationSchemaConstraintsSql;

        var constraints = new Dictionary<string, (bool IsPrimaryKey, bool IsUnique)>(StringComparer.OrdinalIgnoreCase);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            var key = ConstraintKey(reader.GetString(0), reader.GetString(1), reader.GetString(2));
            var isPrimaryKey = string.Equals(reader.GetString(3), "PRIMARY KEY", StringComparison.OrdinalIgnoreCase);

            var existing = constraints.TryGetValue(key, out var current) ? current : (false, false);
            constraints[key] = (existing.Item1 || isPrimaryKey, true);
        }

        return constraints;
    }

    /// <summary>Set of "schema.table.column" keys for columns the database auto-generates (identity/auto-increment
    /// /computed) and therefore can never be written to. Empty for providers without a supported query.</summary>
    private static async Task<HashSet<string>> ReadAutoGeneratedAsync(
        DbConnection connection,
        DestinationType type,
        CancellationToken cancellationToken)
    {
        var sql = type switch
        {
            DestinationType.SqlServer or DestinationType.AzureSql => SqlServerAutoGeneratedSql,
            DestinationType.PostgreSql => PostgresAutoGeneratedSql,
            DestinationType.MySql => MySqlAutoGeneratedSql,
            _ => null,
        };

        var autoGenerated = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (sql is null)
        {
            return autoGenerated;
        }

        await using var command = connection.CreateCommand();
        command.CommandText = sql;

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            autoGenerated.Add(ConstraintKey(reader.GetString(0), reader.GetString(1), reader.GetString(2)));
        }

        return autoGenerated;
    }

    private static string ConstraintKey(string schema, string table, string column) => $"{schema}.{table}.{column}";

    private static string BuildConnectionString(DestinationConnectionProbeRequest request)
    {
        if (!string.IsNullOrWhiteSpace(request.ConnectionString))
        {
            return request.ConnectionString!;
        }

        return request.DestinationType switch
        {
            DestinationType.SqlServer or DestinationType.AzureSql => BuildSqlServerConnectionString(request),
            _ => throw new InvalidOperationException(
                $"Provide a ConnectionString to probe destination type '{request.DestinationType}'."),
        };
    }

    private static string BuildSqlServerConnectionString(DestinationConnectionProbeRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Server) || string.IsNullOrWhiteSpace(request.Database))
        {
            throw new InvalidOperationException("Server and Database are required to test a SQL Server connection.");
        }

        var builder = new SqlConnectionStringBuilder
        {
            DataSource = request.Server,
            InitialCatalog = request.Database,
            TrustServerCertificate = request.TrustServerCertificate,
            Encrypt = request.Encrypt,
            ConnectTimeout = 10,
        };

        switch ((request.Authentication ?? "sql-auth").Trim().ToLowerInvariant())
        {
            case "managed-identity":
                builder.Authentication = SqlAuthenticationMethod.ActiveDirectoryManagedIdentity;
                break;
            case "azure-ad":
                builder.Authentication = SqlAuthenticationMethod.ActiveDirectoryDefault;
                break;
            default: // sql-auth
                builder.UserID = request.Username ?? string.Empty;
                builder.Password = request.Password ?? string.Empty;
                break;
        }

        return builder.ConnectionString;
    }

    private static bool IsRelational(DestinationType type)
        => type is DestinationType.SqlServer or DestinationType.AzureSql or DestinationType.PostgreSql or DestinationType.MySql;

    private static async Task<DbConnection> OpenConnectionAsync(
        DestinationType type,
        string connectionString,
        CancellationToken cancellationToken)
    {
        switch (type)
        {
            case DestinationType.SqlServer:
            case DestinationType.AzureSql:
                return await SqlServerConnectionFactory.OpenConnectionAsync(connectionString, cancellationToken);
            case DestinationType.PostgreSql:
                var npgsql = new NpgsqlConnection(connectionString);
                await npgsql.OpenAsync(cancellationToken);
                return npgsql;
            case DestinationType.MySql:
                var mysql = new MySqlConnection(connectionString);
                await mysql.OpenAsync(cancellationToken);
                return mysql;
            default:
                throw new InvalidOperationException($"Destination type '{type}' is not relational.");
        }
    }

    private const string SqlServerColumnsSql = """
        SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA NOT IN ('sys', 'INFORMATION_SCHEMA')
        ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;
        """;

    private static async Task<List<DestinationTableSchemaDto>> ReadColumnsAsync(
        DbDataReader reader,
        Func<string, string> mapType,
        IReadOnlyDictionary<string, (bool IsPrimaryKey, bool IsUnique)> constraints,
        IReadOnlySet<string> autoGenerated,
        CancellationToken cancellationToken)
    {
        var tables = new Dictionary<string, List<DestinationColumnSchemaDto>>(StringComparer.OrdinalIgnoreCase);
        var tableNames = new Dictionary<string, (string SchemaName, string TableName)>(StringComparer.OrdinalIgnoreCase);

        while (await reader.ReadAsync(cancellationToken))
        {
            var schemaName = reader.GetString(0);
            var tableName = reader.GetString(1);
            var columnName = reader.GetString(2);
            var fullName = $"{schemaName}.{tableName}";
            var dataType = reader.GetString(3);

            // character_maximum_length can exceed int range (e.g. MySQL LONGTEXT) — clamp oversized values to null.
            int? maxLength = null;
            if (!reader.IsDBNull(5))
            {
                var raw = Convert.ToInt64(reader.GetValue(5));
                maxLength = raw is > 0 and <= int.MaxValue ? (int)raw : null;
            }

            if (!tables.TryGetValue(fullName, out var columns))
            {
                columns = [];
                tables[fullName] = columns;
                tableNames[fullName] = (schemaName, tableName);
            }

            var columnKey = ConstraintKey(schemaName, tableName, columnName);
            var (isPrimaryKey, isUnique) = constraints.TryGetValue(columnKey, out var flags)
                ? flags
                : (false, false);

            columns.Add(new DestinationColumnSchemaDto(
                columnName,
                dataType,
                mapType(dataType),
                string.Equals(reader.GetString(4), "YES", StringComparison.OrdinalIgnoreCase),
                maxLength,
                isPrimaryKey,
                isUnique,
                autoGenerated.Contains(columnKey)));
        }

        return tables
            .Select(pair =>
            {
                var (schemaName, tableName) = tableNames[pair.Key];
                return new DestinationTableSchemaDto(schemaName, tableName, pair.Key, pair.Value);
            })
            .ToList();
    }

    private static Func<string, string> MapType(DestinationType type)
        => type switch
        {
            DestinationType.PostgreSql => MapPostgresType,
            DestinationType.MySql => MapMySqlType,
            _ => MapSqlServerType
        };

    private static string MapSqlServerType(string dataType) => dataType.Trim().ToLowerInvariant() switch
    {
        "bit" => "Boolean",
        "tinyint" or "smallint" or "int" or "bigint" => "Integer",
        "decimal" or "numeric" or "money" or "smallmoney" or "float" or "real" => "Decimal",
        "date" => "Date",
        "datetime" or "datetime2" or "datetimeoffset" or "smalldatetime" => "DateTime",
        _ => "String"
    };

    private static string MapPostgresType(string dataType) => dataType.Trim().ToLowerInvariant() switch
    {
        "boolean" => "Boolean",
        "smallint" or "integer" or "bigint" => "Integer",
        "numeric" or "decimal" or "real" or "double precision" or "money" => "Decimal",
        "date" => "Date",
        "timestamp without time zone" or "timestamp with time zone" => "DateTime",
        _ => "String"
    };

    private static string MapMySqlType(string dataType) => dataType.Trim().ToLowerInvariant() switch
    {
        "tinyint" => "Boolean",
        "smallint" or "mediumint" or "int" or "integer" or "bigint" => "Integer",
        "decimal" or "numeric" or "float" or "double" => "Decimal",
        "date" => "Date",
        "datetime" or "timestamp" => "DateTime",
        _ => "String"
    };
}
