// <auto-generated />
using System;
using FHIRBridge.LicenseServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FHIRBridge.LicenseServer.Migrations
{
    [DbContext(typeof(LicenseServerDbContext))]
    partial class LicenseServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FHIRBridge.LicenseServer.Domain.CheckIn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CumulativeConfiguredPipelineRunCount")
                        .HasColumnType("bigint");

                    b.Property<long>("CumulativeRuntimeWorkflowRunCount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CurrentIssuedLicenseId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ObservedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProcessedRecordsThisMonth")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SourceConnectionCount")
                        .HasColumnType("integer");

                    b.Property<int>("TenantCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer");

                    b.Property<int>("WorkflowCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentIssuedLicenseId");

                    b.HasIndex("InstallationId", "ReceivedAtUtc");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("FHIRBridge.LicenseServer.Domain.Installation", b =>
                {
                    b.Property<string>("InstallationId")
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentIssuedLicenseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("Edition")
                        .HasColumnType("text");

                    b.Property<long>("LastCumulativeConfiguredPipelineRunCount")
                        .HasColumnType("bigint");

                    b.Property<long>("LastCumulativeRuntimeWorkflowRunCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastObservedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastProcessedRecordsThisMonth")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastSourceConnectionCount")
                        .HasColumnType("integer");

                    b.Property<int>("LastTenantCount")
                        .HasColumnType("integer");

                    b.Property<int>("LastUserCount")
                        .HasColumnType("integer");

                    b.Property<int>("LastWorkflowCount")
                        .HasColumnType("integer");

                    b.HasKey("InstallationId");

                    b.HasIndex("CurrentIssuedLicenseId");

                    b.HasIndex("LastSeenUtc");

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("FHIRBridge.LicenseServer.Domain.IssuedLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActivationWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("AllowedDestinationTypesSummary")
                        .HasColumnType("text");

                    b.Property<string>("AllowedResourceTypesSummary")
                        .HasColumnType("text");

                    b.Property<string>("AllowedSourceTypesSummary")
                        .HasColumnType("text");

                    b.Property<string>("ClaimsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeaturesSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxProcessedRecordsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSourceConnections")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSuccessfulWorkflowExecutionsPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWorkflows")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IssuedAtUtc");

                    b.ToTable("IssuedLicenses");
                });

            modelBuilder.Entity("FHIRBridge.LicenseServer.Domain.LicenseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FulfilledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FulfilledIssuedLicenseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSubmittedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ReceivedManually")
                        .HasColumnType("boolean");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FulfilledAtUtc");

                    b.HasIndex("FulfilledIssuedLicenseId");

                    b.HasIndex("UniqueKey")
                        .IsUnique();

                    b.ToTable("LicenseRequests");
                });

            modelBuilder.Entity("FHIRBridge.LicenseServer.Domain.CheckIn", b =>
                {
                    b.HasOne("FHIRBridge.LicenseServer.Domain.IssuedLicense", null)
                        .WithMany()
                        .HasForeignKey("CurrentIssuedLicenseId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FHIRBridge.LicenseServer.Domain.Installation", b =>
                {
                    b.HasOne("FHIRBridge.LicenseServer.Domain.IssuedLicense", "CurrentIssuedLicense")
                        .WithMany()
                        .HasForeignKey("CurrentIssuedLicenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentIssuedLicense");
                });

            modelBuilder.Entity("FHIRBridge.LicenseServer.Domain.LicenseRequest", b =>
                {
                    b.HasOne("FHIRBridge.LicenseServer.Domain.IssuedLicense", "FulfilledIssuedLicense")
                        .WithMany()
                        .HasForeignKey("FulfilledIssuedLicenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FulfilledIssuedLicense");
                });
#pragma warning restore 612, 618
        }
    }
}
