using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FHIRBridge.Infrastructure.Migrations.PostgreSql.Migrations
{
    /// <inheritdoc />
    public partial class AddHapiLocalTerminologyAndImportHistory : Migration
    {
        /// <inheritdoc />
        // Guarded raw SQL so re-applying this migration against a database where these columns/tables
        // already exist is a no-op instead of an error — see SyncModelChanges for why this project's
        // Postgres migrations take this defensive approach.
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "WorkflowRuns" ADD COLUMN IF NOT EXISTS "ErrorReferenceId" character varying(50);
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE "PipelineRunRouteExecutions" ADD COLUMN IF NOT EXISTS "ErrorReferenceId" character varying(50);
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "terminology"."HapiTerminologyImportHistory" (
                    "Id" uuid NOT NULL,
                    "CodeSystem" character varying(32) NOT NULL,
                    "Version" character varying(32) NULL,
                    "StartedOnUtc" timestamp with time zone NOT NULL,
                    "CompletedOnUtc" timestamp with time zone NULL,
                    "ImportedConceptCount" integer NOT NULL,
                    "Status" character varying(32) NOT NULL,
                    "ErrorMessage" text NULL,
                    CONSTRAINT "PK_HapiTerminologyImportHistory" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "terminology"."TRM_CODESYSTEM" (
                    "Pid" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "CodeSystemUri" character varying(200) NOT NULL,
                    "CsName" character varying(200) NULL,
                    "CurrentVersionPid" bigint NULL,
                    CONSTRAINT "PK_TRM_CODESYSTEM" PRIMARY KEY ("Pid")
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "terminology"."TRM_CODESYSTEM_VER" (
                    "Pid" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "CodeSystemPid" bigint NOT NULL,
                    "CsVersionId" character varying(200) NOT NULL,
                    "CsDisplay" character varying(200) NULL,
                    CONSTRAINT "PK_TRM_CODESYSTEM_VER" PRIMARY KEY ("Pid")
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "terminology"."TRM_CONCEPT" (
                    "Pid" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "CodeSystemPid" bigint NOT NULL,
                    "CodeVal" character varying(500) NOT NULL,
                    "Display" text NULL,
                    CONSTRAINT "PK_TRM_CONCEPT" PRIMARY KEY ("Pid")
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_HapiTerminologyImportHistory_CodeSystem_StartedOnUtc"
                    ON "terminology"."HapiTerminologyImportHistory" ("CodeSystem", "StartedOnUtc");
                """);

            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_TRM_CODESYSTEM_CodeSystemUri"
                    ON "terminology"."TRM_CODESYSTEM" ("CodeSystemUri");
                """);

            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_TRM_CODESYSTEM_VER_CodeSystemPid_CsVersionId"
                    ON "terminology"."TRM_CODESYSTEM_VER" ("CodeSystemPid", "CsVersionId");
                """);

            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_TRM_CONCEPT_CodeSystemPid_CodeVal"
                    ON "terminology"."TRM_CONCEPT" ("CodeSystemPid", "CodeVal");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_TRM_CONCEPT_CodeVal" ON "terminology"."TRM_CONCEPT" ("CodeVal");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "terminology"."HapiTerminologyImportHistory";
                """);

            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "terminology"."TRM_CODESYSTEM";
                """);

            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "terminology"."TRM_CODESYSTEM_VER";
                """);

            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "terminology"."TRM_CONCEPT";
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE "WorkflowRuns" DROP COLUMN IF EXISTS "ErrorReferenceId";
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE "PipelineRunRouteExecutions" DROP COLUMN IF EXISTS "ErrorReferenceId";
                """);
        }
    }
}
